#!/usr/bin/env python3
# Convert a 64x64 two-colour XPM into the 512-byte icon file init.app reads:
# 64 rows of 8 bytes, most significant bit first, 1 = black.
#
# Copyright (c) 2009 Openmoko Inc.
# Copyright (c) 2026 Tim Douglas
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# The original was a Guile script that wrote each byte with write-char;
# Guile 2 and later encode those as UTF-8, so bytes above 0x7f came out as
# two bytes and init.app rejected the 738-byte result as an invalid icon.

import re
import sys

SIZE = 64


def usage(message=None):
    if message:
        print("error: %s" % message, file=sys.stderr)
    print("usage: %s [--verbose] [--debug] --icon=file xpm-file" % sys.argv[0],
          file=sys.stderr)
    sys.exit(1)


def main(argv):
    icon = None
    sources = []
    for arg in argv[1:]:
        if arg.startswith("--icon="):
            icon = arg[len("--icon="):]
        elif arg in ("--verbose", "-v", "--debug", "-d"):
            pass
        elif arg.startswith("-"):
            usage("unknown option %s" % arg)
        else:
            sources.append(arg)
    if not icon:
        usage("Missing icon-file")
    if len(sources) != 1:
        usage("need exactly one source file")

    strings = re.findall(r'"((?:[^"\\]|\\.)*)"', open(sources[0]).read())
    if len(strings) < 3 + SIZE:
        usage("source file is not a 64x64 2 colour XPM file")
    header = strings[0].split()
    if header[:4] != [str(SIZE), str(SIZE), "2", "1"]:
        usage("source file is not a 64x64 2 colour XPM file")
    colours = {}
    for entry in strings[1:3]:
        colours[entry[0]] = entry.split("c", 1)[1].strip().upper()
    black = [c for c, v in colours.items() if v in ("#000000", "BLACK")]
    if len(colours) != 2 or len(black) != 1:
        usage("the two colours must be #FFFFFF and #000000")
    black = black[0]

    out = bytearray()
    for row in strings[3:3 + SIZE]:
        if len(row) < SIZE:
            usage("pixel row shorter than %d" % SIZE)
        for byte in range(SIZE // 8):
            value = 0
            for pixel in row[byte * 8:byte * 8 + 8]:
                value = value * 2 + (1 if pixel == black else 0)
            out.append(value)
    with open(icon, "wb") as f:
        f.write(bytes(out))


if __name__ == "__main__":
    main(sys.argv)
