#!/usr/bin/env python3
"""
Generate a self-checking C program for the differential harness.

The same source is compiled by c33-epson-elf-gcc (3.3.2) and run in the
emulator, and by the host compiler and run natively. Divergence means the
emulator executes at least one instruction differently from what the
compiler meant by it.

Everything is written to avoid undefined behaviour, because UB would let the
two compilers legitimately disagree and produce false alarms: arithmetic is
done in unsigned, shift counts are masked, divisors are guarded, and the
only implementation-defined step is the u32 -> i32 conversion, which both
compilers implement as two's complement.
"""

import random
import sys

# Binary operators over u32. Signed ones cast explicitly at the point of use.
BINOPS = [
    ('{a} + {b}',                    'add'),
    ('{a} - {b}',                    'sub'),
    ('{a} * {b}',                    'mul'),
    ('{a} & {b}',                    'and'),
    ('{a} | {b}',                    'or'),
    ('{a} ^ {b}',                    'xor'),
    ('{a} << SH({b})',               'sll'),
    ('{a} >> SH({b})',               'srl'),
    ('(u32)((i32){a} >> SH({b}))',   'sra'),
    ('DIVU({a}, {b})',               'divu'),
    ('MODU({a}, {b})',               'modu'),
    ('(u32)DIVS((i32){a}, (i32){b})', 'divs'),
    ('(u32)MODS((i32){a}, (i32){b})', 'mods'),
    ('((u32)((i32){a} < (i32){b}))',  'lts'),
    ('((u32)({a} < {b}))',            'ltu'),
    ('((u32)({a} == {b}))',           'eq'),
    ('((u32)((i32){a} >= (i32){b}))', 'ges'),
    # sign/zero extension through narrow types
    ('((u32)(signed char){a}',        'extb'),
    ('((u32)(unsigned char){a}',      'extub'),
    ('((u32)(short){a}',              'exth'),
    ('((u32)(unsigned short){a}',     'extuh'),
    # rotate idioms -- gcc turns these into rl/rr, which no firmware image uses
    ('(({a} << SH({b})) | ({a} >> ((32 - SH({b})) & 31)))',  'rl'),
    ('(({a} >> SH({b})) | ({a} << ((32 - SH({b})) & 31)))',  'rr'),
    # 16x16 multiplies, which map to mlt.h / mltu.h rather than mlt.w
    ('((u32)((short){a} * (short){b}))',                     'mlth'),
    # NB both operands promote to int, so (unsigned short)a * (unsigned short)b
    # overflows INT_MAX for products above 0x7fffffff -- undefined, and the
    # host optimiser exploits it. Cast to u32 so the multiply is unsigned.
    ('((u32)(unsigned short){a} * (u32)(unsigned short){b})', 'mltuh'),
]

UNOPS = [
    '(~{a})',
    '(0u - {a})',                # negating (i32)INT_MIN would overflow
    '((u32)(signed char){a})',
    '((u32)(unsigned char){a})',
    '((u32)(short){a})',
    '((u32)(unsigned short){a})',
    '({a} ? {a} - 1u : {a} + 1u)',
]

# Immediates chosen to straddle every field width the ISA has, so the ext
# prefix machinery gets exercised at each boundary.
IMMS = [0, 1, 2, 3, 7, 8, 15, 16, 31, 32, 63, 64, 0x7f, 0x80, 0xff, 0x100,
        0x1fff, 0x2000, 0x7fff, 0x8000, 0xffff, 0x10000, 0x3ffff, 0x40000,
        0x7fffffff, 0x80000000, 0xffffffff, 0xdeadbeef, 0xcafebabe]


def expr(rng, vars_, depth):
    if depth <= 0 or (vars_ and rng.random() < 0.35):
        if vars_ and rng.random() < 0.7:
            return rng.choice(vars_)
        return '0x%08xu' % rng.choice(IMMS)
    if rng.random() < 0.2:
        return rng.choice(UNOPS).format(a=expr(rng, vars_, depth - 1))
    tmpl, _ = rng.choice(BINOPS)
    # the narrow-cast entries are unary in disguise; close the paren
    if tmpl.count('{b}') == 0:
        return tmpl.format(a=expr(rng, vars_, depth - 1)) + ')'
    return '(' + tmpl.format(a=expr(rng, vars_, depth - 1),
                             b=expr(rng, vars_, depth - 1)) + ')'


def gen(seed):
    rng = random.Random(seed)
    out = []
    w = out.append

    w('/* Generated by gen.py -- seed %d. Do not edit. */' % seed)
    w('#include "dt.h"')
    w('')

    # --- helper functions with varying arity, to exercise the argument ABI.
    # r6..r9 pass the first four; anything beyond goes on the stack.
    nfns = rng.randint(3, 6)
    for i in range(nfns):
        argc = rng.randint(1, 8)
        params = ', '.join('u32 p%d' % j for j in range(argc))
        body_vars = ['p%d' % j for j in range(argc)]
        w('static u32 fn%d(%s)' % (i, params))
        w('{')
        w('\tu32 t = %s;' % expr(rng, body_vars, 3))
        w('\treturn t;')
        w('}')
        w('')

    # --- a recursive function, to pile up stack frames
    w('static u32 rec(u32 n, u32 acc)')
    w('{')
    w('\tif (n == 0)')
    w('\t\treturn acc;')
    w('\treturn rec(n - 1, %s);' % expr(rng, ['n', 'acc'], 2))
    w('}')
    w('')

    # --- a function with a large frame, to exercise [%sp+imm] beyond imm6
    w('static u32 bigframe(u32 s)')
    w('{')
    w('\tu32 a[200];')
    w('\tint i;')
    w('\tfor (i = 0; i < 200; i++)')
    w('\t\ta[i] = s + (u32)i * 2654435761u;')
    w('\tfor (i = 0; i < 200; i++)')
    w('\t\ts = %s;' % expr(rng, ['s', 'a[i]'], 2))
    w('\treturn s;')
    w('}')
    w('')

    # --- byte and halfword memory traffic, signed and unsigned
    w('static u32 memops(u32 s)')
    w('{')
    w('\tunsigned char b[16];')
    w('\tshort h[8];')
    w('\tunsigned short uh[8];')
    w('\tint i;')
    w('\tu32 r = s;')
    w('\tfor (i = 0; i < 16; i++)')
    w('\t\tb[i] = (unsigned char)(s >> (i & 7));')
    w('\tfor (i = 0; i < 8; i++) {')
    w('\t\th[i] = (short)(s * (u32)(i + 1));')
    w('\t\tuh[i] = (unsigned short)(s ^ (u32)i);')
    w('\t}')
    w('\tfor (i = 0; i < 16; i++)')
    w('\t\tr = r * 31u + (u32)(signed char)b[i];')
    w('\tfor (i = 0; i < 8; i++)')
    w('\t\tr = r * 17u + (u32)h[i] + (u32)uh[i];')
    w('\treturn r;')
    w('}')
    w('')

    # --- single-bit set/clear on memory, which gcc emits as bset/bclr
    w('struct bits { u32 w[4]; unsigned char b[8]; };')
    w('static u32 bitops(u32 s)')
    w('{')
    w('\tstruct bits v;')
    w('\tint i;')
    w('\tfor (i = 0; i < 4; i++)')
    w('\t\tv.w[i] = s * (u32)(i + 1);')
    w('\tfor (i = 0; i < 8; i++)')
    w('\t\tv.b[i] = (unsigned char)(s >> i);')
    for k in range(8):
        bit = rng.randrange(32)
        idx = rng.randrange(4)
        if rng.random() < 0.5:
            w('\tv.w[%d] |= 0x%08xu;' % (idx, 1 << bit))
        else:
            w('\tv.w[%d] &= ~0x%08xu;' % (idx, 1 << bit))
    for k in range(6):
        bit = rng.randrange(8)
        idx = rng.randrange(8)
        if rng.random() < 0.5:
            w('\tv.b[%d] |= 0x%02xu;' % (idx, 1 << bit))
        else:
            w('\tv.b[%d] &= (unsigned char)~0x%02xu;' % (idx, 1 << bit))
    w('\tfor (i = 0; i < 4; i++)')
    w('\t\ts = s * 33u + v.w[i];')
    w('\tfor (i = 0; i < 8; i++)')
    w('\t\ts = s * 7u + v.b[i];')
    w('\treturn s;')
    w('}')
    w('')

    # --- switch, which gcc may turn into a jump table
    w('static u32 sw(u32 s)')
    w('{')
    w('\tswitch (s & 15) {')
    for k in range(16):
        w('\tcase %d: return %s;' % (k, expr(rng, ['s'], 2)))
    w('\t}')
    w('\treturn s;')
    w('}')
    w('')

    # --- 64-bit arithmetic: forces multi-word add/subtract sequences
    w('static u32 wide(u32 s)')
    w('{')
    w('\tunsigned long long x = ((unsigned long long)s << 32) | (s ^ 0x9e3779b9u);')
    w('\tunsigned long long y = ((unsigned long long)(s ^ 0x5bf03635u) << 32) | s;')
    w('\tunsigned long long z = x + y;')
    w('\tz ^= x - y;')
    w('\tz += x * 3ull;')
    w('\tz ^= z >> 17;')
    w('\tz += (unsigned long long)s << 40;')
    w('\treturn (u32)(z >> 32) ^ (u32)z;')
    w('}')
    w('')

    # --- main: a stream of values, each depending on the last
    w('int main(void)')
    w('{')
    w('\tu32 s = 0x12345678u;')
    w('\tint i;')
    w('')
    nsteps = rng.randint(40, 80)
    for _ in range(nsteps):
        kind = rng.random()
        if kind < 0.45:
            w('\ts = %s;' % expr(rng, ['s'], 4))
        elif kind < 0.62:
            i_fn = rng.randrange(nfns)
            argc = None
            # recover this function's arity from the emitted prototype
            for line in out:
                if line.startswith('static u32 fn%d(' % i_fn):
                    argc = line.count('u32 p')
                    break
            args = ', '.join(expr(rng, ['s'], 1) for _ in range(argc))
            w('\ts = fn%d(%s);' % (i_fn, args))
        elif kind < 0.70:
            w('\ts = rec(%d, s);' % rng.randint(1, 12))
        elif kind < 0.78:
            w('\ts = bigframe(s);')
        elif kind < 0.86:
            w('\ts = memops(s);')
        elif kind < 0.90:
            w('\ts = sw(s);')
        elif kind < 0.94:
            w('\ts = bitops(s);')
        else:
            w('\ts = wide(s);')
        w('\temit(s);')
    w('')
    # a loop at the end, so control flow is not purely straight-line
    w('\tfor (i = 0; i < 37; i++) {')
    w('\t\ts = %s;' % expr(rng, ['s', '(u32)i'], 3))
    w('\t\temit(s);')
    w('\t}')
    w('\treturn 0;')
    w('}')
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    sys.stdout.write(gen(int(sys.argv[1]) if len(sys.argv) > 1 else 1))
