/*
 * Epson C33 instruction execution.
 *
 * Decoding is a flat table lookup (c33_forms.h, generated by disassembling
 * all 65536 encodings with binutils) so there is no mask-precedence logic
 * here to get wrong -- the derived opcode/mask pairs genuinely overlap.
 */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>

#include "c33.h"
#include "../c33_forms.h"
#include "../c33_syscalls.h"

/* ---- operand extraction --------------------------------------------- */

static int32_t fld(uint16_t insn, const struct c33_field *f)
{
	int32_t v = (insn >> f->shift) & ((1u << f->width) - 1);
	if (f->is_signed && (v >> (f->width - 1)))
		v -= (int32_t)1 << f->width;
	return v;
}

/* Instructions are 16 bits, so every value loaded into PC loses bit 0. */
static uint32_t pc_value(uint32_t value)
{
	return value & ~1u;
}

static uint32_t psr_value(uint32_t value)
{
	return value & (PSR_IL_MASK | PSR_IE | PSR_C | PSR_V | PSR_Z | PSR_N);
}

/*
 * Combine any pending ext prefixes with a base immediate of the given width.
 * Consumes the prefixes.
 */
static uint32_t imm_ext(struct c33 *c, uint32_t base, unsigned width)
{
	uint32_t v;

	if (c->n_ext == 0)
		v = base;
	else if (c->n_ext == 1)
		v = (c->ext[0] << width) | base;
	else
		v = (c->ext[0] << (width + 13)) | (c->ext[1] << width) | base;

	c->n_ext = 0;
	return v;
}

/*
 * Data immediates on the arithmetic/logic/move forms are sign-extended from
 * the composed width, e.g. "cmp %r6,0x3f" with no prefix means -1 (objdump
 * renders it xcmp %r6,0xffffffff). Verified against every widened no-prefix
 * site in grifo.elf: and 0x30->0xfffffff0, cmp 0x3f->0xffffffff,
 * ld.w 0x3c->0xfffffffc.
 *
 * Memory displacements ([%sp+imm], [%dp+imm]) and shift counts are NOT
 * sign-extended and keep using imm_ext().
 */
static uint32_t imm_ext_s(struct c33 *c, uint32_t base, unsigned width)
{
	unsigned n = c->n_ext;
	unsigned T = width + 13 * n;
	uint32_t v = imm_ext(c, base, width);

	if (T < 32 && ((v >> (T - 1)) & 1))
		v |= ~((1u << T) - 1);
	return v;
}

/*
 * PC-relative displacements are signed, but objdump prints the raw field
 * unsigned (jrne -3 shows as "jrne 253"), so the generated tables mark them
 * unsigned. Sign-extend from the *composed* width: 8 bits alone, 21 with one
 * ext prefix, 34 (i.e. no truncation) with two.
 */
static int32_t disp_ext(struct c33 *c, uint32_t base, unsigned width)
{
	unsigned n = c->n_ext;
	uint32_t e0 = n > 0 ? c->ext[0] : 0;
	uint32_t e1 = n > 1 ? c->ext[1] : 0;
	uint32_t v;
	unsigned T;

	c->n_ext = 0;

	if (n == 0) {
		v = base;
		T = width;
	} else if (n == 1) {
		v = (e0 << width) | base;
		T = width + 13;
	} else {
		/*
		 * Two prefixes, per the C33 PE Core manual's "call sign8"
		 * entry (Extension 2):
		 *
		 *   ext  imm13 ; imm13(12:3) = sign32(31:22)
		 *   ext  imm13 ; = sign32(21:9)
		 *   call sign8 ; sign8 = sign32(8:1), sign32(0) = 0
		 *
		 * Only bits 12:3 of the FIRST prefix take part; its low three
		 * bits are discarded rather than shifted in. Working in word
		 * units (this returns a halfword displacement that the caller
		 * doubles) that is ext1[12:3] at 21, ext2 at 8, sign8 at 0,
		 * signed across 31 bits.
		 */
		v = ((e0 >> 3) << 21) | (e1 << width) | base;
		T = 31;
	}

	if (T < 32) {
		v &= (1u << T) - 1;
		if ((v >> (T - 1)) & 1)
			v |= ~((1u << T) - 1);
	}
	return (int32_t)v;
}


/*
 * Displacement for [%sp+imm] / [%dp+imm].
 *
 * The short 6-bit field is scaled by the access size: the compiler emits
 * ld.w [%sp+0x0] and ld.w [%sp+0x1] for two consecutive words, and
 * Serial_printf's varargs walk depends on the second landing at byte 4.
 *
 * The ext-composed form is instead a plain byte offset, like the
 * ext-prefixed [%rN] form (xld.w [%r15+0x3ed60] composes exactly 0x3ed60
 * and adds it directly). wiki.app spills fd to [%sp+0x304] inside a
 * 776-byte frame (pushn %r3; sub %sp,0xc2) -- 0x304 = 772 as bytes, but
 * 3088 if scaled, which lands outside the frame entirely.
 */
static uint32_t sp_disp(struct c33 *c, uint32_t base, unsigned width,
			unsigned size)
{
	unsigned n = c->n_ext;
	uint32_t v = imm_ext(c, base, width);

	return n ? v : v * size;
}

/* ---- memory helpers -------------------------------------------------- */

/*
 * Halfword and word accesses must sit on their natural boundary; otherwise
 * the processor raises the address misaligned exception (vector 6) and the
 * access does not happen. The manual notes SP-based loads can never trip
 * this, because their displacement is scaled by the access size.
 *
 * Off by default: it is primarily a way to catch emulator bugs, and turning
 * a silent unaligned access into a trap changes behaviour.
 */
#define VECTOR_ADDRESS_MISALIGNED 6

static void take_irq(struct c33 *c);
static void take_exception(struct c33 *c, unsigned vector, uint32_t return_pc);
/*
 * Executed-opcode histogram, most-used first.
 *
 * Static disassembly cannot answer "which instructions does this binary
 * actually run" -- objdump decodes rodata and jump tables as instructions
 * too, which is how a binary with no div.w in it appears to contain 30 of
 * them. This counts what the CPU retired.
 */
void c33_dump_profile(const struct c33 *c, FILE *out)
{
	unsigned order[256], n = 0;

	for (unsigned i = 0; i < 256 && i < OP_COUNT; i++)
		if (c->opcount[i])
			order[n++] = i;
	for (unsigned i = 0; i < n; i++)
		for (unsigned j = i + 1; j < n; j++)
			if (c->opcount[order[j]] > c->opcount[order[i]]) {
				unsigned t = order[i]; order[i] = order[j]; order[j] = t;
			}

	fprintf(out, "--- opcodes executed: %u distinct ---\n", n);
	for (unsigned i = 0; i < n; i++)
		fprintf(out, "OP %-10s %lu\n",
			c33_op_name[order[i]], c->opcount[order[i]]);
}

/*
 * Executed instructions per 1K of address space, hottest first. The opcode
 * histogram says what is running; this says where, which is what you need
 * when the mix looks ordinary but the total does not.
 */
void c33_dump_pcprofile(const struct c33 *c, FILE *out)
{
	if (!c->pcbuckets)
		return;
	unsigned long total = 0;
	for (unsigned i = 0; i < C33_PCBUCKETS; i++)
		total += c->pcbuckets[i];
	fprintf(out, "--- hottest code (1K buckets) ---\n");
	for (unsigned shown = 0; shown < 12; shown++) {
		unsigned best = 0;
		for (unsigned i = 0; i < C33_PCBUCKETS; i++)
			if (c->pcbuckets[i] > c->pcbuckets[best])
				best = i;
		if (!c->pcbuckets[best])
			break;
		fprintf(out, "PC %08x  %12lu  %5.1f%%\n",
			c->pcsample[best] & ~((1u << C33_PCBUCKET_SHIFT) - 1),
			c->pcbuckets[best],
			total ? 100.0 * c->pcbuckets[best] / total : 0.0);
		((struct c33 *)c)->pcbuckets[best] = 0;
		}
		}

void c33_dump_pcprofile_full(const struct c33 *c, FILE *out)
{
	if (!c->pcbuckets)
		return;
	for (unsigned i = 0; i < C33_PCBUCKETS; i++)
		if (c->pcbuckets[i])
			fprintf(out, "%08x %lu\n",
				c->pcsample[i] & ~((1u << C33_PCBUCKET_SHIFT) - 1),
				c->pcbuckets[i]);
}

void c33_raise_irq(struct c33 *c, unsigned vector, unsigned priority);

static bool misaligned(struct c33 *c, uint32_t a, unsigned sz)
{
	if (sz < 2 || (a & (sz - 1)) == 0)
		return false;

	c->misaligned_hits++;
	c->access_fault = true;
	/* The faulting load is retried after reti (Core Manual 6.3.5). */
	take_exception(c, VECTOR_ADDRESS_MISALIGNED, c->cur_pc);
	return true;
}

static uint32_t rd(struct c33 *c, uint32_t a, unsigned sz)
{
	if (misaligned(c, a, sz))
		return 0;

	/* Same region cache as the fetch path; see c33_step. */
	if (a >= c->data_lo && a < c->data_hi && c->data_hi - a >= sz) {
		uint32_t v = 0;
		memcpy(&v, c->data_ptr + (a - c->data_lo), sz);
		return v;
	}
	if (c->bus.region) {
		uint32_t base, len;
		uint8_t *p = c->bus.region(c->bus.ctx, a, &base, &len);
		if (p && a >= base && a - base <= len - sz) {
			c->data_ptr = p;
			c->data_lo  = base;
			c->data_hi  = base + len;
			uint32_t v = 0;
			memcpy(&v, p + (a - base), sz);
			return v;
		}
	}
	return c->bus.read(c->bus.ctx, a, sz);
}

static void wr(struct c33 *c, uint32_t a, unsigned sz, uint32_t v)
{
	if (misaligned(c, a, sz))
		return;
	c->bus.write(c->bus.ctx, a, sz, v);
}

/* ---- flags ----------------------------------------------------------- */

/*
 * Z and N from a result, leaving C and V alone. This is what the shift and
 * rotate instructions do: the C33 PE Core manual lists them as
 * "IE C V Z N / - - - <-> <->".
 */
static void set_nz(struct c33 *c, uint32_t v)
{
	uint32_t p = c->sr[SR_PSR] & ~(PSR_N | PSR_Z);
	if (v == 0)
		p |= PSR_Z;
	if (v & 0x80000000u)
		p |= PSR_N;
	c->sr[SR_PSR] = p;
}

/*
 * As above but also clearing V, which is what the logical operations do:
 * and/or/xor/not are listed as "- - 0 <-> <->", so V is forced to zero
 * while C is untouched.
 */
static void set_nz_clrv(struct c33 *c, uint32_t v)
{
	set_nz(c, v);
	c->sr[SR_PSR] &= ~PSR_V;
}

static void set_add_flags(struct c33 *c, uint32_t a, uint32_t b, uint64_t res)
{
	uint32_t r = (uint32_t)res;
	uint32_t p = c->sr[SR_PSR] & ~(PSR_N | PSR_Z | PSR_C | PSR_V);
	if (r == 0)
		p |= PSR_Z;
	if (r & 0x80000000u)
		p |= PSR_N;
	if (res >> 32)
		p |= PSR_C;
	if (~(a ^ b) & (a ^ r) & 0x80000000u)
		p |= PSR_V;
	c->sr[SR_PSR] = p;
}

static void set_sub_flags(struct c33 *c, uint32_t a, uint32_t b)
{
	uint32_t r = a - b;
	uint32_t p = c->sr[SR_PSR] & ~(PSR_N | PSR_Z | PSR_C | PSR_V);
	if (r == 0)
		p |= PSR_Z;
	if (r & 0x80000000u)
		p |= PSR_N;
	if (a < b)
		p |= PSR_C;            /* borrow */
	if ((a ^ b) & (a ^ r) & 0x80000000u)
		p |= PSR_V;
	c->sr[SR_PSR] = p;
}

static void set_adc_flags(struct c33 *c, uint32_t a, uint32_t b,
			  unsigned carry, uint64_t result)
{
	int64_t signed_result = (int64_t)(int32_t)a + (int32_t)b + carry;
	uint32_t r = (uint32_t)result;
	uint32_t p = c->sr[SR_PSR] & ~(PSR_N | PSR_Z | PSR_C | PSR_V);

	if (r == 0)
		p |= PSR_Z;
	if (r & 0x80000000u)
		p |= PSR_N;
	if (result >> 32)
		p |= PSR_C;
	if (signed_result > INT32_MAX || signed_result < INT32_MIN)
		p |= PSR_V;
	c->sr[SR_PSR] = p;
}

static void set_sbc_flags(struct c33 *c, uint32_t a, uint32_t b,
			  unsigned borrow, uint64_t subtrahend)
{
	int64_t signed_result = (int64_t)(int32_t)a - (int32_t)b - borrow;
	uint32_t r = a - (uint32_t)subtrahend;
	uint32_t p = c->sr[SR_PSR] & ~(PSR_N | PSR_Z | PSR_C | PSR_V);

	if (r == 0)
		p |= PSR_Z;
	if (r & 0x80000000u)
		p |= PSR_N;
	if ((uint64_t)a < subtrahend)
		p |= PSR_C;
	if (signed_result > INT32_MAX || signed_result < INT32_MIN)
		p |= PSR_V;
	c->sr[SR_PSR] = p;
}

/* Condition codes used by the jr<cc> family. */
static bool cond(const struct c33 *c, uint8_t op)
{
	uint32_t p = c->sr[SR_PSR];
	bool N = p & PSR_N, Z = p & PSR_Z, V = p & PSR_V, C = p & PSR_C;

	switch (op) {
	case OP_JREQ: case OP_JREQ_D:     return Z;
	case OP_JRNE: case OP_JRNE_D:     return !Z;
	case OP_JRGT: case OP_JRGT_D:     return !Z && (N == V);
	case OP_JRGE: case OP_JRGE_D:     return N == V;
	case OP_JRLT: case OP_JRLT_D:     return N != V;
	case OP_JRLE: case OP_JRLE_D:     return Z || (N != V);
	case OP_JRUGT: case OP_JRUGT_D:   return !C && !Z;
	case OP_JRUGE: case OP_JRUGE_D:   return !C;
	case OP_JRULT: case OP_JRULT_D:   return C;
	case OP_JRULE: case OP_JRULE_D:   return C || Z;
	default:                          return false;
	}
}

static bool is_delayed(uint8_t op)
{
	switch (op) {
	case OP_JREQ_D: case OP_JRNE_D: case OP_JRGT_D: case OP_JRGE_D:
	case OP_JRLT_D: case OP_JRLE_D: case OP_JRUGT_D: case OP_JRUGE_D:
	case OP_JRULT_D: case OP_JRULE_D: case OP_JP_D: case OP_CALL_D:
	case OP_JPR_D: case OP_RET_D:
		return true;
	default:
		return false;
	}
}

/*
 * The generated decoder is deliberately the union of the STD, ADV and PE
 * instruction sets.  Most instructions removed from PE have their own
 * opcode enum and are rejected in c33_step's undefined-instruction cases,
 * but a few ADV encodings reuse a mnemonic which PE also implements.
 * Recognizing the mnemonic is therefore not sufficient to admit the form.
 *
 * The PE opcode table has no class-7 instructions (the %dp-relative memory
 * family), and the PE Core Manual documents only ext imm13.  The class-0
 * add-to-DP form is likewise an Advanced-core instruction.
 */
static bool pe_encoding_valid(uint16_t insn, const struct c33_form *f)
{
	if ((insn & 0xe000u) == 0xe000u)
		return false;
	if (f->op == OP_ADD && f->shape_id == SHAPE_R_DP)
		return false;
	if (f->op == OP_EXT && f->shape_id != SHAPE_I)
		return false;
	return true;
}

/*
 * Cycle costs, from the CLK line of each entry in the C33 PE Core manual.
 *
 * ext itself is listed as "zero or one cycle depending on the instruction
 * queue status"; one is charged here as the upper bound, so elapsed time
 * errs slightly long rather than short.
 */
static unsigned cycle_cost(uint8_t op, const struct c33_form *f,
			   uint16_t insn, bool conditional_taken, bool had_ext)
{
	unsigned n;

	switch (op) {
	case OP_INT:                            return 7;
	case OP_MLT_W: case OP_MLTU_W:          return 7;
	case OP_MLT_H: case OP_MLTU_H:          return 5;
	case OP_BRK:                            return 9;
	case OP_HALT: case OP_SLP: case OP_RETI: case OP_RETD: return 5;
	case OP_RET:                            return 4;
	case OP_RET_D:                          return 3;
	case OP_PSRSET: case OP_PSRCLR:         return 3;
	case OP_PUSH:                           return 2;
	case OP_PUSHN: case OP_POPN:            return (insn & 0xfu) + 2;
	case OP_PUSHS: case OP_POPS:            return (insn & 0xfu) == SR_AHR ? 3 : 2;
	case OP_LD_W:
		if (f->sreg == 1 && (insn & 0xfu) == SR_PSR)
			return 3;
		break;
	case OP_BSET: case OP_BCLR: case OP_BNOT: return had_ext ? 4 : 3;
	case OP_BTST:                           return had_ext ? 3 : 2;
	case OP_CALL:                           return 4;
	case OP_CALL_D:                         return 3;
	case OP_JP: case OP_JPR:                return 3;
	case OP_JP_D: case OP_JPR_D:            return 2;
	case OP_EXT:                            return 1;
	default:
		break;
	}

	/* Post-increment and SP-relative transfers always take two clocks. */
	switch (f->shape_id) {
	case SHAPE_R_LRBP: case SHAPE_LRBP_R:
	case SHAPE_R_LSPPIB: case SHAPE_LSPPIB_R:
		return 2;
	default:
		break;
	}

	/* conditional branches: two cycles, three when taken; .d always two */
	if (is_delayed(op))
		return 2;
	switch (op) {
	case OP_JREQ: case OP_JRNE: case OP_JRGT: case OP_JRGE:
	case OP_JRLT: case OP_JRLE: case OP_JRUGT: case OP_JRUGE:
	case OP_JRULT: case OP_JRULE:
		return conditional_taken ? 3 : 2;
	default:
		break;
	}

	n = 1;
	if (had_ext && (op == OP_LD_W || op == OP_LD_B || op == OP_LD_UB ||
			op == OP_LD_H || op == OP_LD_UH))
		n = 2;
	return n;
}

/* ---- shape classification -------------------------------------------- */
/*
 * Several operations share a mnemonic across very different addressing
 * modes (ld.w alone has 30+ forms). The generated form carries the operand
 * `shape` string objdump printed, which distinguishes them exactly.
 */
/*
 * Shapes are interned to integers by the table generator (enum c33_shape).
 * This used to strcmp against the shape string, which profiled as the
 * single hottest thing in the interpreter: forms are tested as an if/else
 * chain, so a common instruction like ld.w walked several string compares
 * on every execution.
 */

/*
 * Reset clears the whole struct, not a hand-maintained list of fields.
 *
 * The bus and the flags callers set before reset are saved and restored
 * around the wipe. Zeroing field by field has caught this project out three
 * times now -- each new counter added to struct c33 read back as whatever
 * was on the caller's stack, most memorably reporting six billion executed
 * instructions in a six-hundred-million instruction run.
 */
void c33_reset(struct c33 *c, uint32_t entry)
{
	/*
	 * Machine state only. The host-side wiring lives past the barrier and
	 * is deliberately untouched -- see the comment on it in c33.h. An
	 * earlier version listed the fields to save and restore by hand, and
	 * every field added after that was silently zeroed on reset.
	 */
	memset(c, 0, offsetof(struct c33, reset_barrier__));
	c->pc = pc_value(entry);
	/* Fixed cold-reset values from Core Manual sections 2.5, 2.7, 2.8. */
	c->sr[SR_TTBR] = 0x00c00000;
	c->sr[SR_IDIR] = 0x06000000; /* PE type; revision/model is unspecified */
	c->sr[SR_DBBR] = 0x00060000;
}

void c33_raise_irq(struct c33 *c, unsigned vector, unsigned priority)
{
	/*
	 * A cause that is disabled in the controller never reaches the CPU.
	 * Checking here rather than only at delivery matters because there
	 * is one pending slot: a disabled source that got as far as being
	 * recorded would displace a live request and then be discarded,
	 * losing both. That is how an unwanted timer 2 wake-up was eating
	 * touch interrupts.
	 */
	if (c->irq_enabled && !c->irq_enabled(c->irq_ctx, vector))
		return;

	c->irq_pending = true;
	c->irq_vector = vector;
	c->irq_priority = priority;
}

/*
 * Take a pending hardware interrupt. The frame matches the software trap
 * exactly -- return PC then PSR -- because grifo's handlers are ordinary
 * __attribute__((interrupt_handler)) functions that exit with reti.
 */
static void take_irq(struct c33 *c)
{
	uint32_t target = c->bus.read(c->bus.ctx,
				      c->sr[SR_TTBR] + c->irq_vector * 4, 4);

	/*
	 * "Maskable interrupt requests are accepted only when their priority
	 * levels are higher than that set in the IL bit field. When an
	 * interrupt request is accepted, the IL bit field is set to the
	 * priority level of that interrupt" (C33 PE Core manual, 2.3.1).
	 * The saved PSR restores the old IL on reti.
	 */
	/*
	 * A raised request can be withdrawn before it is taken. grifo's
	 * resume path does exactly that: it arms timer 2 as a wake source,
	 * halts, and then disables and clears that interrupt before
	 * re-enabling interrupts. Delivering it anyway lands in grifo's
	 * "Panic: undefined interrupt".
	 */
	if (c->irq_enabled && !c->irq_enabled(c->irq_ctx, c->irq_vector)) {
		c->irq_pending = false;
		return;
	}

	unsigned il = (c->sr[SR_PSR] & PSR_IL_MASK) >> PSR_IL_SHIFT;
	if (c->irq_priority <= il) {
		c->irqs_masked++;
		return;              /* stays pending until IL drops */
	}

	c->irq_pending = false;
	if (!target)
		return;              /* no handler installed yet */

	c->sr[SR_SP] -= 4;
	c->bus.write(c->bus.ctx, c->sr[SR_SP], 4, c->pc);
	c->sr[SR_SP] -= 4;
	c->bus.write(c->bus.ctx, c->sr[SR_SP], 4, c->sr[SR_PSR]);
	c->sr[SR_PSR] &= ~PSR_IE;
	c->sr[SR_PSR] = (c->sr[SR_PSR] & ~PSR_IL_MASK) |
			(c->irq_priority << PSR_IL_SHIFT);
	c->pc = pc_value(target);
	c->irqs_taken++;
}

/*
 * Enter a synchronous processor exception.  Unlike a maskable external
 * interrupt, this path neither consults the interrupt controller nor tests
 * or rewrites PSR.IL.  Core Manual 6.3.3 specifies the common frame: save PC
 * then PSR, clear IE, and load the handler from TTBR + vector * 4.
 */
static void take_exception(struct c33 *c, unsigned vector, uint32_t return_pc)
{
	uint32_t target = c->bus.read(c->bus.ctx,
				      c->sr[SR_TTBR] + vector * 4, 4);

	c->sr[SR_SP] -= 4;
	c->bus.write(c->bus.ctx, c->sr[SR_SP], 4, return_pc);
	c->sr[SR_SP] -= 4;
	c->bus.write(c->bus.ctx, c->sr[SR_SP], 4, c->sr[SR_PSR]);
	c->sr[SR_PSR] &= ~PSR_IE;
	c->pc = pc_value(target);
	c->delay_pending = false;
}

/* Architectural restrictions on the special-register transfer forms. */
static bool read_sreg(const struct c33 *c, unsigned reg, uint32_t *value)
{
	switch (reg) {
	case SR_PSR: case SR_SP: case SR_ALR: case SR_AHR:
	case SR_TTBR: case SR_IDIR: case SR_DBBR:
		*value = c->sr[reg];
		return true;
	case SR_PC:
		/* ld.w %rd,%pc reads the following address (section 2.2). */
		*value = c->pc;
		return true;
	default:
		return false;
	}
}

static void write_sreg(struct c33 *c, unsigned reg, uint32_t value)
{
	switch (reg) {
	case SR_PSR:
		c->sr[reg] = psr_value(value);
		break;
	case SR_SP:
		c->sr[reg] = value & ~3u;
		break;
	case SR_TTBR:
		c->sr[reg] = value & ~0x3ffu;
		break;
	case SR_ALR:
	case SR_AHR:
		c->sr[reg] = value;
		break;
	case SR_IDIR:
	case SR_DBBR:
	case SR_PC:
		break;                  /* read-only, or PC's defined no-op write */
	default:
		break;                  /* not a PE special register: instruction nop */
	}
}

static void fault(struct c33 *c, const char *why)
{
	if (!c->fault) {
		c->fault = why;
		c->fault_pc = c->cur_pc;
	}
	c->halted = true;
}

void c33_step(struct c33 *c)
{
	if (c->halted)
		return;

	/*
	 * Asleep in HALT: retire no instructions, but let time pass so the
	 * timers keep running and a pending interrupt can arrive. The cycle
	 * counter advances too, so instruction limits and scripted input
	 * still work against a sleeping machine.
	 */
	if (c->sleeping) {
		/*
		 * Time still has to pass -- the wake-up is a timer -- but the
		 * caller decides how far to jump, because only it knows when
		 * the next thing is due. Ticking one cycle per call here kept
		 * a host core busy doing nothing.
		 *
		 * It does advance by one, though, so the cycle counter is
		 * always monotonic. Returning without moving it lets a caller
		 * see the same cycle number twice, and anything watching for
		 * an exact count -- scripted input, for one -- fires twice.
		 */
		c->cycles++;
		c->sleep_cycles++;
		/*
		 * "The interrupt enable/disable status set in the processor
		 *  does not affect the cancellation of HALT or SLEEP modes...
		 *  interrupt signals are able to cancel HALT and SLEEP modes
		 *  even if the IE flag in PSR or the interrupt enable bits in
		 *  the interrupt controller are set to disable interrupts."
		 *                        (C33 PE Core manual, HALT/SLEEP)
		 *
		 * So a request wakes the core whatever IE says; it is only
		 * the taking of it that IE gates. This matters because grifo
		 * suspends with interrupts disabled and expects to be woken.
		 */
		if (c->irq_pending) {
			c->sleeping = false;
			if (c->sr[SR_PSR] & PSR_IE)
				take_irq(c);
		}
		return;
	}

	/*
	 * An interrupt must not be taken part-way through an ext sequence.
	 *
	 *   "For exceptions associated with ext instructions, exception
	 *    handling is started immediately for reset and debug break, but is
	 *    not started for other exceptions until after the target
	 *    instruction to be extended is executed."
	 *                              (C33 PE Core manual, 5.6.3)
	 *
	 * Taking one mid-sequence discards the prefixes already seen, so the
	 * target instruction computes a truncated immediate, and the leftover
	 * state leaks into the handler's first instruction. That is not
	 * theoretical: a touch interrupt landing between the two prefixes of
	 *
	 *     ext 0x200 ; ext 0x353 ; ld.w %r0,0x2c   -> 0x1000d4ec
	 *
	 * in grifo's syscall return made it load from 0xd4ec instead, which
	 * read as zero and sent an indirect ret to address 0.
	 */
	if (c->irq_pending && !c->debug_mode && (c->sr[SR_PSR] & PSR_IE) &&
	    !c->delay_pending && !c->n_ext)
		take_irq(c);

	uint32_t at = c->pc;
	c->access_fault = false;

	/* A syscall has returned once execution resumes past its .short. */
	if (c->trace_syscalls && c->sysret_pc && at == c->sysret_pc) {
		const char *nm = (c->sysret_num <= C33_SYSCALL_MAX &&
				  c33_syscall_name[c->sysret_num])
			       ? c33_syscall_name[c->sysret_num] : "?";
		fprintf(stderr, "  RET %-22s -> r4=%08x (%d)\n",
			nm, c->r[4], (int32_t)c->r[4]);
		c->sysret_pc = 0;
	}

	c->cur_pc = at;

	/*
	 * Fetch fast path.
	 *
	 * The generic path is an indirect call into mem_read followed by a
	 * search of the memory map, for every instruction. Caching the region
	 * the PC currently sits in turns the common case into a bounds check
	 * and a load. The cache holds a pointer into the same buffer rather
	 * than a copy, so writes through the bus stay visible.
	 */
	uint16_t insn;
	/*
	 * Written to avoid wrapping: "at + 2 <= fetch_hi" would be true for
	 * an address near 0xffffffff, letting a wild PC index far outside the
	 * region. A stray jump is exactly when this path must not misbehave.
	 */
	if (at >= c->fetch_lo && at < c->fetch_hi && c->fetch_hi - at >= 2) {
		memcpy(&insn, c->fetch_ptr + (at - c->fetch_lo), 2);
	} else if (c->bus.region) {
		uint32_t base, len;
		uint8_t *p = c->bus.region(c->bus.ctx, at, &base, &len);
		if (p && at >= base && at - base <= len - 2) {
			c->fetch_ptr = p;
			c->fetch_lo  = base;
			c->fetch_hi  = base + len;
			memcpy(&insn, p + (at - base), 2);
		} else {
			insn = (uint16_t)rd(c, at, 2);
			if (c->access_fault)
				return;
		}
	} else {
		insn = (uint16_t)rd(c, at, 2);
		if (c->access_fault)
			return;
	}
	c->last_insn = insn;
	const struct c33_form *f = &c33_forms[c33_form_of[insn]];
	uint8_t op = pe_encoding_valid(insn, f) ? f->op : OP_INVALID;
	if (c->profile)
		c->opcount[op]++;
	if (c->pc_profile) {
		unsigned b = (at >> C33_PCBUCKET_SHIFT) & (C33_PCBUCKETS - 1);
		c->pcbuckets[b]++;
		c->pcsample[b] = at;   /* buckets alias; keep a real address */
	}

	c->pc = at + 2;
	c->cycles++;

	int32_t a = f->nfields > 0 ? fld(insn, &f->f[0]) : 0;
	int32_t b = f->nfields > 1 ? fld(insn, &f->f[1]) : 0;
	bool had_ext = c->n_ext != 0;
	bool conditional_taken = false;

	bool was_delayed = c->delay_pending;
	uint32_t delay_to = c->delay_target;

	switch (op) {
	case OP_INVALID:
	case OP_DIV0S: case OP_DIV0U: case OP_DIV1: case OP_DIV2S: case OP_DIV3S:
	case OP_MAC: case OP_MIRROR: case OP_SCAN0: case OP_SCAN1:
	case OP_DIV_W: case OP_DIVU_W: case OP_LOOP:
	case OP_MAC_HW: case OP_MAC_W: case OP_MAC1_H: case OP_MAC1_HW:
	case OP_MAC1_W: case OP_MACCLR: case OP_MLT_HW: case OP_REPEAT:
	case OP_RETM: case OP_SAT_B: case OP_SAT_H: case OP_SAT_UB:
	case OP_SAT_UH: case OP_SAT_UW: case OP_SAT_W:
		/*
		 * Nine instructions exist on the STD core but are explicitly
		 * removed from PE (S1C33E07 Table I.5.3.5).  The remaining cases
		 * above are ADV-only instructions which likewise are not in the PE
		 * instruction table.  The disassembler-derived decoder recognizes
		 * all core variants, so the PE executor must reject both groups.  An
		 * undefined word is recorded in IDIR, acts as a nop, and vectors
		 * through TTBR + 0x0c with the following PC saved (6.3.9).
		 */
		c->sr[SR_IDIR] = (c->sr[SR_IDIR] & 0xffff0000u) | insn;
		take_exception(c, 3, c->pc);
		break;

	/* ---- ext prefix ------------------------------------------------ */
	case OP_EXT:
		if (c->n_ext < 2) {
			c->ext[c->n_ext++] = (uint32_t)a;
		} else {
			/*
			 * "this processor has come to generate an
			 * exception when ... more than two ext
			 * instructions are described" -- S1C33E07
			 * manual B.3. Vector 2 is the ext exception.
			 */
			c->n_ext = 0;
			/* Save the first prefix, not the third (6.3.10). */
			take_exception(c, 2, c->cur_pc - 4);
		}
		return;   /* prefixes never complete an instruction */

	case OP_NOP:
		break;

	case OP_HALT:
		/*
		 * HALT stops the core until an interrupt, it does not stop the
		 * machine. Treating it as a stop was harmless while nothing
		 * reached it, but grifo's suspend path halts and waits for the
		 * touch controller to wake it, so ending the run there made
		 * the device unresponsive the moment it first went idle.
		 */
		c->sleeping = true;
		break;

	case OP_SLP:
		/*
		 * S1C33E07 III.1.11.2: WAKEUPWT=0 auto-wakes after the clock
		 * switch; WAKEUPWT=1 waits for reset or an interrupt. With no
		 * SoC callback, retain the core manual's ordinary sleep behavior.
		 */
		if (!c->slp_auto_wake || !c->slp_auto_wake(c->slp_ctx))
			c->sleeping = true;
		break;

	/* ---- moves and loads ------------------------------------------- */
	case OP_LD_W:
		if ((f->shape_id == SHAPE_R_I)) {                    /* immediate */
			c->r[a] = imm_ext_s(c, (uint32_t)b, f->f[1].width);
		} else if ((f->shape_id == SHAPE_R_R)) {
			c->r[a] = c->r[b];
		} else if ((f->shape_id == SHAPE_R_LRB)) {
			/* an ext prefix turns [%rs] into [%rs+imm] */
			uint32_t v = rd(c, c->r[b] + imm_ext(c, 0, 0), 4);
			if (!c->access_fault)
				c->r[a] = v;
		} else if ((f->shape_id == SHAPE_R_LRBP)) {
			uint32_t addr = c->r[b];
			uint32_t v = rd(c, addr, 4);
			if (!c->access_fault) {
				c->r[b] = addr + 4;
				if (a != b)
					c->r[a] = v;
			}
		} else if ((f->shape_id == SHAPE_LRB_R)) {
			wr(c, c->r[a] + imm_ext(c, 0, 0), 4, c->r[b]);
		} else if ((f->shape_id == SHAPE_LRBP_R)) {
			wr(c, c->r[a], 4, c->r[b]);
			if (!c->access_fault)
				c->r[a] += 4;
		} else if ((f->shape_id == SHAPE_R_LSPPIB)) {
			uint32_t v = rd(c, c->sr[SR_SP] +
					sp_disp(c, (uint32_t)b, f->f[1].width, 4), 4);
			if (!c->access_fault)
				c->r[a] = v;
		} else if ((f->shape_id == SHAPE_LSPPIB_R)) {
			wr(c, c->sr[SR_SP] +
			   sp_disp(c, (uint32_t)a, f->f[0].width, 4), 4, c->r[b]);
		} else if ((f->shape_id == SHAPE_R_LDPPIB)) {
			uint32_t v = rd(c, c->sr[SR_DP] +
					sp_disp(c, (uint32_t)b, f->f[1].width, 4), 4);
			if (!c->access_fault)
				c->r[a] = v;
		} else if ((f->shape_id == SHAPE_LDPPIB_R)) {
			wr(c, c->sr[SR_DP] +
			   sp_disp(c, (uint32_t)a, f->f[0].width, 4), 4, c->r[b]);
		} else if (f->sreg == 1) {
			/* ld.w %sreg,%rN  (0xa00N): index is bits 3:0 */
			write_sreg(c, insn & 0xf, c->r[a]);
		} else if (f->sreg == 2) {
			/* ld.w %rN,%sreg  (0xa4N0): index is bits 7:4 */
			uint32_t value;
			if (read_sreg(c, (insn >> 4) & 0xf, &value))
				c->r[a] = value;
		} else {
			fault(c, "unhandled ld.w form");
		}
		break;

	case OP_LD_B:
	case OP_LD_UB:
	case OP_LD_H:
	case OP_LD_UH: {
		unsigned sz = (op == OP_LD_B || op == OP_LD_UB) ? 1 : 2;
		bool sext = (op == OP_LD_B || op == OP_LD_H);
		if ((f->shape_id == SHAPE_R_R)) {
			/* register-to-register: narrow then extend, no memory */
			uint32_t v = c->r[b] & (sz == 1 ? 0xffu : 0xffffu);
			if (sext)
				v = sz == 1 ? (uint32_t)(int8_t)v
					    : (uint32_t)(int16_t)v;
			c->r[a] = v;
		} else if ((f->shape_id == SHAPE_R_LRB) || (f->shape_id == SHAPE_R_LRBP)) {
			uint32_t off = (f->shape_id == SHAPE_R_LRB) ? imm_ext(c, 0, 0) : 0;
			uint32_t addr = c->r[b] + off;
			uint32_t v = rd(c, addr, sz);
			if (sext && !c->access_fault)
				v = sz == 1 ? (uint32_t)(int8_t)v
					    : (uint32_t)(int16_t)v;
			if (!c->access_fault) {
				if ((f->shape_id == SHAPE_R_LRBP)) {
					c->r[b] = addr + sz;
					if (a != b)
						c->r[a] = v;
				} else {
					c->r[a] = v;
				}
			}
		} else if ((f->shape_id == SHAPE_LRB_R) || (f->shape_id == SHAPE_LRBP_R)) {
			uint32_t off = (f->shape_id == SHAPE_LRB_R) ? imm_ext(c, 0, 0) : 0;
			wr(c, c->r[a] + off, sz, c->r[b]);
			if ((f->shape_id == SHAPE_LRBP_R) && !c->access_fault)
				c->r[a] += sz;
		} else if ((f->shape_id == SHAPE_R_LSPPIB)) {
			uint32_t v = rd(c, c->sr[SR_SP] +
					sp_disp(c, (uint32_t)b, f->f[1].width, sz),
					sz);
			if (sext && !c->access_fault)
				v = sz == 1 ? (uint32_t)(int8_t)v
					    : (uint32_t)(int16_t)v;
			if (!c->access_fault)
				c->r[a] = v;
		} else if ((f->shape_id == SHAPE_LSPPIB_R)) {
			wr(c, c->sr[SR_SP] +
			   sp_disp(c, (uint32_t)a, f->f[0].width, sz), sz, c->r[b]);
		} else {
			fault(c, "unhandled ld.b/h form");
		}
		break;
	}

	/* ---- arithmetic ------------------------------------------------- */
	case OP_ADC: {
		unsigned carry = !!(c->sr[SR_PSR] & PSR_C);
		uint64_t s = (uint64_t)c->r[a] + c->r[b] + carry;
		set_adc_flags(c, c->r[a], c->r[b], carry, s);
		c->r[a] = (uint32_t)s;
		break;
	}

	case OP_SBC: {
		unsigned borrow = !!(c->sr[SR_PSR] & PSR_C);
		uint64_t subtrahend = (uint64_t)c->r[b] + borrow;
		set_sbc_flags(c, c->r[a], c->r[b], borrow, subtrahend);
		c->r[a] -= (uint32_t)subtrahend;
		break;
	}

	case OP_ADD:
		if ((f->shape_id == SHAPE_R_R)) {
			if (c->n_ext) {
				/*
				 * An ext prefix on a register-register form
				 * turns it into rd = rs + imm, the immediate
				 * being the general rule with base width 0.
				 * gcc uses this for string addresses:
				 * ext 0x2; ext 0x175c; add %r6,%r15
				 * gives __dp + 0x575c, which is exactly where
				 * grifo's message strings live.
				 */
				uint32_t i = imm_ext(c, 0, 0);
				uint64_t s = (uint64_t)c->r[b] + i;
				set_add_flags(c, c->r[b], i, s);
				c->r[a] = (uint32_t)s;
				break;
			}
			uint64_t s = (uint64_t)c->r[a] + c->r[b];
			set_add_flags(c, c->r[a], c->r[b], s);
			c->r[a] = (uint32_t)s;
		} else if ((f->shape_id == SHAPE_R_I)) {
			/* add/sub zero-extend: the assembler picks the opposite
			 * mnemonic rather than a negative immediate. Measured
			 * over 56 sites in grifo.elf + the arithmetic test. */
			uint32_t i = imm_ext(c, (uint32_t)b, f->f[1].width);
			uint64_t s = (uint64_t)c->r[a] + i;
			set_add_flags(c, c->r[a], i, s);
			c->r[a] = (uint32_t)s;
		} else if ((f->shape_id == SHAPE_SP_I)) {
			/* imm10 counts words: SP must stay 4-aligned for popn
			 * and ld.w [%sp+n]. objdump prints the raw field.  ext is
			 * explicitly unusable for this form and acts as a nop. */
			c->sr[SR_SP] += (uint32_t)a * 4;
		} else if ((f->shape_id == SHAPE_R_DP)) {
			c->r[a] += c->sr[SR_DP];
		} else {
			fault(c, "unhandled add form");
		}
		break;

	case OP_SUB:
		if ((f->shape_id == SHAPE_R_R)) {
			if (c->n_ext) {
				uint32_t i = imm_ext(c, 0, 0);
				set_sub_flags(c, c->r[b], i);
				c->r[a] = c->r[b] - i;
			} else {
				set_sub_flags(c, c->r[a], c->r[b]);
				c->r[a] -= c->r[b];
			}
		} else if ((f->shape_id == SHAPE_R_I)) {
			uint32_t i = imm_ext(c, (uint32_t)b, f->f[1].width);
			set_sub_flags(c, c->r[a], i);
			c->r[a] -= i;
		} else if ((f->shape_id == SHAPE_SP_I)) {
			/* As with add %sp, ext does not extend this operand. */
			c->sr[SR_SP] -= (uint32_t)a * 4;
		} else {
			fault(c, "unhandled sub form");
		}
		break;

	case OP_CMP:
		if ((f->shape_id == SHAPE_R_R)) {
			if (c->n_ext) {
				uint32_t i = imm_ext(c, 0, 0);
				set_sub_flags(c, c->r[b], i);
			} else {
				set_sub_flags(c, c->r[a], c->r[b]);
			}
		}
		else if ((f->shape_id == SHAPE_R_I))
			set_sub_flags(c, c->r[a],
				      imm_ext_s(c, (uint32_t)b, f->f[1].width));
		else
			fault(c, "unhandled cmp form");
		break;

	case OP_AND:
	case OP_OR:
	case OP_XOR: {
		uint32_t rhs;
		if ((f->shape_id == SHAPE_R_R)) {
			if (c->n_ext) {
				rhs = imm_ext(c, 0, 0);
				c->r[a] = c->r[b];
			} else {
				rhs = c->r[b];
			}
		}
		else if ((f->shape_id == SHAPE_R_I))
			rhs = imm_ext_s(c, (uint32_t)b, f->f[1].width);
		else { fault(c, "unhandled logic form"); break; }
		c->r[a] = op == OP_AND ? (c->r[a] & rhs)
		       : op == OP_OR  ? (c->r[a] | rhs)
				      : (c->r[a] ^ rhs);
		set_nz_clrv(c, c->r[a]);
		break;
	}

	case OP_NOT:
		if ((f->shape_id == SHAPE_R_R))
			c->r[a] = ~c->r[b];
		else if ((f->shape_id == SHAPE_R_I))
			c->r[a] = ~imm_ext_s(c, (uint32_t)b, f->f[1].width);
		else { fault(c, "unhandled not form"); break; }
		set_nz_clrv(c, c->r[a]);
		break;

	/* ---- shifts ----------------------------------------------------- */
	case OP_SRL:
	case OP_SLL:
	case OP_SRA:
	case OP_SLA:
	case OP_RL:
	case OP_RR: {
		uint32_t n = (f->shape_id == SHAPE_R_R) ? (c->r[b] & 31)
						    : ((uint32_t)b & 31);
		uint32_t v = c->r[a];
		switch (op) {
		case OP_SRL: v = n ? v >> n : v; break;
		case OP_SLL: case OP_SLA: v = n ? v << n : v; break;
		case OP_SRA: v = n ? (uint32_t)((int32_t)v >> n) : v; break;
		case OP_RL:  v = n ? (v << n) | (v >> (32 - n)) : v; break;
		case OP_RR:  v = n ? (v >> n) | (v << (32 - n)) : v; break;
		}
		c->r[a] = v;
		set_nz(c, v);
		break;
	}

	/* ---- stack ------------------------------------------------------ */
	/*
	 * pushn %rN saves r0..rN (not rN..r15). The operand distribution in
	 * grifo.elf makes this unambiguous: pushn %r1 and %r3 dominate, which
	 * under the other reading would mean almost every function saves 15
	 * registers. Saving r0..r3 is the callee-saved set, and it crucially
	 * leaves r4 -- the return value register -- alone. Getting this
	 * backwards made popn clobber every function's return value.
	 */
	/*
	 * Push order: rN goes to the highest address and r0 ends up at [sp+0].
	 * grifo's syscall handler documents its frame after "pushn %r1" as
	 * ( return pc psr r1 r0 ) reading high to low, i.e. r0 at [sp+0] --
	 * and it indexes that frame directly, so the order is observable and
	 * not merely a symmetric push/pop convention.
	 */
	case OP_PUSHN:
		for (int i = a; i >= 0; i--) {
			c->sr[SR_SP] -= 4;
			wr(c, c->sr[SR_SP], 4, c->r[i]);
		}
		break;

	case OP_POPN:
		for (int i = 0; i <= a; i++) {
			c->r[i] = rd(c, c->sr[SR_SP], 4);
			c->sr[SR_SP] += 4;
		}
		break;

	case OP_PUSH:
		c->sr[SR_SP] -= 4;
		wr(c, c->sr[SR_SP], 4, c->r[a]);
		break;

	case OP_POP:
		c->r[a] = rd(c, c->sr[SR_SP], 4);
		c->sr[SR_SP] += 4;
		break;

	/* ---- control transfer ------------------------------------------- */
	case OP_CALL:
	case OP_CALL_D:
	case OP_JP:
	case OP_JP_D: {
		uint32_t target;
		if ((f->shape_id == SHAPE_R)) {
			/* Register branch targets always have their LSB handled as 0. */
			target = pc_value(c->r[a]);
			c->n_ext = 0;
		} else {
			/* PC-relative, word displacement, measured from the
			 * base instruction rather than the first ext prefix. */
			int32_t s = disp_ext(c, (uint32_t)a, f->f[0].width);
			target = at + ((uint32_t)s << 1);
		}
		if (op == OP_CALL || op == OP_CALL_D) {
			/*
			 * The return address goes on the stack, not into a
			 * link register: r15 is the global data pointer
			 * (__dp), set up at boot by xld.w %r15,__dp. For
			 * call.d the delay-slot instruction at at+2 still
			 * runs, so the return lands at at+4.
			 */
			uint32_t ra = (op == OP_CALL_D) ? at + 4 : at + 2;
			c->sr[SR_SP] -= 4;
			wr(c, c->sr[SR_SP], 4, ra);
		}
		if (is_delayed(op)) {
			c->delay_pending = true;
			c->delay_target = target;
		} else {
			c->pc = target;
		}
		break;
	}

	case OP_RET:
		c->pc = pc_value(rd(c, c->sr[SR_SP], 4));
		if (!c->access_fault)
			c->sr[SR_SP] += 4;
		break;

	case OP_RET_D: {
		uint32_t target = pc_value(rd(c, c->sr[SR_SP], 4));
		if (!c->access_fault) {
			c->sr[SR_SP] += 4;
			c->delay_pending = true;
			c->delay_target = target;
		}
		break;
	}

	case OP_JPR:
	case OP_JPR_D: {
		/* jpr likewise treats its signed register displacement as even. */
		uint32_t target = at + pc_value(c->r[a]);
		if (op == OP_JPR_D) {
			c->delay_pending = true;
			c->delay_target = target;
		} else {
			c->pc = target;
		}
		break;
	}

	case OP_JREQ: case OP_JREQ_D: case OP_JRNE: case OP_JRNE_D:
	case OP_JRGT: case OP_JRGT_D: case OP_JRGE: case OP_JRGE_D:
	case OP_JRLT: case OP_JRLT_D: case OP_JRLE: case OP_JRLE_D:
	case OP_JRUGT: case OP_JRUGT_D: case OP_JRUGE: case OP_JRUGE_D:
	case OP_JRULT: case OP_JRULT_D: case OP_JRULE: case OP_JRULE_D: {
		int32_t d = disp_ext(c, (uint32_t)a, f->f[0].width);
		uint32_t target = at + ((uint32_t)d << 1);
		bool taken = cond(c, op);
		conditional_taken = taken;
		if (is_delayed(op)) {
			/* The branch-to-slot window masks interrupts even when the
			 * condition is false.  In that case retiring the slot selects
			 * the instruction after it, just as sequential execution would. */
			c->delay_pending = true;
			c->delay_target = taken ? target : at + 4;
		} else if (taken) {
			c->pc = target;
		}
		break;
	}

	/* ---- multiply: 64-bit product into AHR:ALR ----------------------- */
	case OP_MLT_W:
	case OP_MLTU_W: {
		/* grifo reads the result back with ld.w %rN,%alr */
		uint64_t p;
		if (op == OP_MLT_W)
			p = (uint64_t)(int64_t)((int32_t)c->r[a] *
						(int64_t)(int32_t)c->r[b]);
		else
			p = (uint64_t)c->r[a] * (uint64_t)c->r[b];
		c->sr[SR_ALR] = (uint32_t)p;
		c->sr[SR_AHR] = (uint32_t)(p >> 32);
		break;
	}

	case OP_MLT_H:
	case OP_MLTU_H: {
		/* 16 x 16 -> 32, taking the low halfword of each operand */
		uint32_t r;
		if (op == OP_MLT_H)
			r = (uint32_t)((int32_t)(int16_t)c->r[a] *
				       (int32_t)(int16_t)c->r[b]);
		else
			r = (uint32_t)((c->r[a] & 0xffff) * (c->r[b] & 0xffff));
		c->sr[SR_ALR] = r;
		break;
	}

	case OP_SWAP: {
		uint32_t v = c->r[b];
		c->r[a] = ((v & 0x000000ffu) << 24) |
			  ((v & 0x0000ff00u) << 8)  |
			  ((v & 0x00ff0000u) >> 8)  |
			  ((v & 0xff000000u) >> 24);
		break;
	}

	case OP_SWAPH: {
		uint32_t v = c->r[b];
		c->r[a] = ((v & 0x00ff00ffu) << 8) |
			  ((v & 0xff00ff00u) >> 8);
		break;
	}

	/* ---- push/pop of a special register ------------------------------ */
	/*
 * pushs/pops move ALR alone or the AHR:ALR pair, with ALR at [sp+0].
 * Although the four-bit encoding can name every special register, the
 * instruction pages permit only ALR and AHR and explicitly define every
 * other value as a no-op.
	 */
	case OP_PUSHS:
		if ((insn & 0xf) == SR_ALR || (insn & 0xf) == SR_AHR)
			for (int i = (int)(insn & 0xf); i >= SR_ALR; i--) {
				c->sr[SR_SP] -= 4;
				wr(c, c->sr[SR_SP], 4, c->sr[i]);
			}
		break;

	case OP_POPS:
		if ((insn & 0xf) == SR_ALR || (insn & 0xf) == SR_AHR)
			for (int i = SR_ALR; i <= (int)(insn & 0xf); i++) {
				c->sr[i] = rd(c, c->sr[SR_SP], 4);
				c->sr[SR_SP] += 4;
			}
		break;

	/* ---- bit operations on a byte in memory -------------------------- */
	case OP_BSET:
	case OP_BCLR:
	case OP_BNOT:
	case OP_BTST: {
		/* shape "[%r#],#": field0 is the address register, field1 the
		 * bit number (3 bits, so a byte operand). */
		uint32_t addr = c->r[a] + imm_ext(c, 0, 0);   /* ext -> [%rN+imm] */
		uint32_t bit = 1u << (b & 7);
		uint32_t v = rd(c, addr, 1);
		if (op == OP_BTST) {
			uint32_t p = c->sr[SR_PSR] & ~PSR_Z;
			if (!(v & bit))
				p |= PSR_Z;
			c->sr[SR_PSR] = p;
		} else {
			v = op == OP_BSET ? (v | bit)
			  : op == OP_BCLR ? (v & ~bit)
					  : (v ^ bit);
			wr(c, addr, 1, v & 0xff);
		}
		break;
	}

	/* ---- system ------------------------------------------------------ */
	/*
	 * imm5 is a bit number, not a mask: "values 0, 1, 2, 3, and 4
	 * representing bits 0 (N), 1 (Z), 2 (V), 3 (C), and 4 (IE)... An imm5
	 * of more than 4 is not effective and does not alter the contents of
	 * PSR" (C33 PE Core manual, psrset).
	 */
	case OP_PSRSET:
		if (a <= 4)
			c->sr[SR_PSR] |= 1u << a;
		break;

	case OP_PSRCLR:
		if (a <= 4)
			c->sr[SR_PSR] &= ~(1u << a);
		break;

	case OP_BRK:
		/*
		 * Software debug exception, Core Manual sections 6.5 and 7:
		 * save the following PC and R0 in the fixed debug area, then
		 * branch through its vector.  This is deliberately not the normal
		 * exception stack frame.  Hardware and NMI interrupts remain
		 * pending while the processor is in debug mode.
		 */
		wr(c, c->sr[SR_DBBR] + 0x08, 4, c->pc);
		wr(c, c->sr[SR_DBBR] + 0x0c, 4, c->r[0]);
		if (!c->access_fault) {
			c->pc = pc_value(rd(c, c->sr[SR_DBBR], 4));
			if (!c->access_fault)
				c->debug_mode = true;
		}
		break;

	/*
	 * Software interrupt -- grifo's syscall mechanism. A stub is:
	 *
	 *     file_open:  int 1
	 *                 .short 111
	 *
	 * The handler reads [%sp+3] (= sp+12, after its own pushn %r1 saves
	 * two words) to find the return PC, which points at that .short and
	 * gives the syscall number. So int pushes the return PC first, then
	 * the PSR. Vector numbering is from grifo/src/vector.h:
	 * VECTOR_Software_exception_0 = 12, so int n uses vector 12 + n, and
	 * the table base lives in TTBR.
	 */
	case OP_INT: {
		uint32_t vec = 12u + ((uint32_t)a & 3u);
		uint32_t target = rd(c, c->sr[SR_TTBR] + vec * 4, 4);

		if (a == 1) {
			/* the halfword at the return PC is the syscall index */
			unsigned n = (unsigned)rd(c, c->pc, 2);
			c->syscalls++;
			/*
			 * The stub has no ret: grifo's handler rewrites the
			 * exit point and returns straight to whoever called
			 * the stub. That address is what `call` pushed, still
			 * on top of the stack as we take the trap.
			 */
			c->sysret_pc = rd(c, c->sr[SR_SP], 4);
			c->sysret_num = n;
			if (c->trace_syscalls) {
				const char *nm = (n <= C33_SYSCALL_MAX &&
						  c33_syscall_name[n])
					       ? c33_syscall_name[n] : "?";
				/* r6,r7,r8 carry the first arguments */
				fprintf(stderr,
					"  SYS %-22s (%u)  r6=%08x r7=%08x r8=%08x"
					"  from=%08x\n",
					nm, n, c->r[6], c->r[7], c->r[8],
					c->sysret_pc);
			}
		}

		c->sr[SR_SP] -= 4;
		wr(c, c->sr[SR_SP], 4, c->pc);          /* return PC = at + 2 */
		c->sr[SR_SP] -= 4;
		wr(c, c->sr[SR_SP], 4, c->sr[SR_PSR]);
		c->sr[SR_PSR] &= ~PSR_IE;               /* enter with ints off */
		c->pc = pc_value(target);
		break;
	}

	case OP_RETI: {
		/* The manual orders these reads PC first, then PSR, then SP update. */
		uint32_t sp = c->sr[SR_SP];
		uint32_t target = rd(c, sp + 4, 4);
		if (c->access_fault)
			break;
		uint32_t status = rd(c, sp, 4);
		if (c->access_fault)
			break;
		c->pc = pc_value(target);
		c->sr[SR_PSR] = psr_value(status);
		c->sr[SR_SP] = sp + 8;
		break;
	}

	case OP_RETD:
		/* Debug save area layout, Core Manual retd instruction page. */
		c->r[0] = rd(c, c->sr[SR_DBBR] + 0x0c, 4);
		if (!c->access_fault) {
			c->pc = pc_value(rd(c, c->sr[SR_DBBR] + 0x08, 4));
			if (!c->access_fault)
				c->debug_mode = false;
		}
		break;

	default:
		fault(c, c33_op_name[op]);
		break;
	}

	/*
	 * ext prefixes modify exactly the next instruction. Any that the
	 * handler above did not consume are discarded here -- otherwise a
	 * form we decode but whose immediate we ignore would leak its
	 * prefixes into the following instruction.
	 */
	/* Charge MCLK cycles; a taken conditional branch costs one more. */
	c->clk += cycle_cost(op, f, insn, conditional_taken, had_ext);

	if (c->n_ext) {
		/*
		 * The handler above did not consume the prefixes, so this form
		 * is not yet implementing ext-supplied immediates. Count it:
		 * every non-zero entry here is a latent addressing bug.
		 */
		unsigned fi = c33_form_of[insn];
		c->ext_dropped[fi < 256 ? fi : 255]++;
	}
	c->n_ext = 0;

	/* Retire a pending delay-slot branch after its slot has executed. */
	if (was_delayed && c->delay_pending && !c->halted) {
		c->delay_pending = false;
		c->pc = delay_to;
	}
}

void c33_report_dropped_ext(const struct c33 *c, FILE *out)
{
	unsigned shown = 0;
	for (unsigned i = 0; i < 256; i++) {
		if (!c->ext_dropped[i])
			continue;
		const struct c33_form *f = &c33_forms[i];
		fprintf(out, "  %-9s %-16s %u\n", c33_op_name[f->op],
			f->shape[0] ? f->shape : "-", c->ext_dropped[i]);
		shown++;
	}
	if (!shown)
		fprintf(out, "  (none)\n");
}

void c33_disasm(const struct c33 *c, uint32_t addr, char *buf, size_t len)
{
	struct c33 *m = (struct c33 *)c;
	uint16_t insn = (uint16_t)m->bus.read(m->bus.ctx, addr, 2);
	const struct c33_form *f = &c33_forms[c33_form_of[insn]];

	if (f->nfields == 0) {
		snprintf(buf, len, "%04x  %-8s %s", insn,
			 c33_op_name[f->op], f->shape);
		return;
	}
	int32_t a = fld(insn, &f->f[0]);
	if (f->nfields == 1)
		snprintf(buf, len, "%04x  %-8s %-14s %d", insn,
			 c33_op_name[f->op], f->shape, a);
	else
		snprintf(buf, len, "%04x  %-8s %-14s %d, %d", insn,
			 c33_op_name[f->op], f->shape, a,
			 fld(insn, &f->f[1]));
}
