#!/usr/bin/env python3
"""Generate the C33 PE valid-encoding bitmap from PE ELF disassembly."""

import re
import sys
from pathlib import Path


def main():
    source = Path(sys.argv[1] if len(sys.argv) > 1 else "allinsn_pe.txt")
    output = Path(sys.argv[2] if len(sys.argv) > 2 else "c33_pe_valid.h")
    valid = [False] * 65536
    seen = set()
    for line in source.read_text().splitlines():
        match = re.match(
            r"^\s*([0-9a-f]+):\s+([0-9a-f]{2}) ([0-9a-f]{2})\s+(\S+)",
            line,
        )
        if not match:
            continue
        address = int(match.group(1), 16)
        word = int(match.group(3) + match.group(2), 16)
        index = address // 2
        if address & 1 or index >= 65536 or word != index:
            raise ValueError(f"unexpected all-word disassembly line: {line}")
        seen.add(index)
        mnemonic = match.group(4)
        # binutils appends *** both for reserved operand values which the
        # manual defines as no-ops and for violations of fixed opcode bits.
        # Only the actual 0x009_ / 0x00d_ pushs/pops families get the former
        # treatment; accepting every word binutils labels with those names
        # also admits 0x00b_, 0x00c_, 0x00e_, and 0x00f_.
        documented_field_nop = (
            (mnemonic == "ld.w" and (word & 0xff00) in (0xa000, 0xa400))
            or (mnemonic == "pushs" and word & 0xfff0 == 0x0090)
            or (mnemonic == "pops" and word & 0xfff0 == 0x00d0)
        )
        valid[index] = (mnemonic != ".short"
                        and ("***" not in line
                             or documented_field_nop))

    # The forward-ported EPSON opcode table historically had two overly
    # broad masks.  Current in-tree binutils fixes them at the source; keep
    # these constraints as a guard when regenerating with an older or
    # externally supplied C33 objdump.  They come from the C33 PE Core
    # manual's encoding diagrams and are independently enforced by GMMan's
    # SLEIGH definition:
    #
    #   ld.cf             is exactly 0x01d0; bits 3:0 are fixed zero
    #   psrset/psrclr     have bit 5 fixed zero
    #
    # Operand values 5..31 in the real psr forms remain valid instructions;
    # the manual defines them as ineffective, so do not reject those.
    for word in range(0x01d1, 0x01e0):
        valid[word] = False
    for word in range(0xbf60, 0xbf80):
        valid[word] = False
    for word in range(0xbfa0, 0xbfc0):
        valid[word] = False

    if len(seen) != 65536:
        raise ValueError(f"found {len(seen)} words, expected 65536")

    bitmap = []
    for base in range(0, 65536, 8):
        bitmap.append(sum(int(valid[base + bit]) << bit for bit in range(8)))

    lines = [
        "/* Generated by tools/gen_pe_valid.py -- do not edit.",
        " * PE binutils decode, refined by manual fixed-bit constraints.",
        " */",
        "#ifndef C33_PE_VALID_H",
        "#define C33_PE_VALID_H",
        "",
        "#include <stdint.h>",
        "",
        "static const uint8_t c33_pe_valid[8192] = {",
    ]
    for start in range(0, len(bitmap), 16):
        lines.append("\t" + ", ".join(
            f"0x{value:02x}" for value in bitmap[start:start + 16]) + ",")
    lines += ["};", "", "#endif /* C33_PE_VALID_H */", ""]
    output.write_text("\n".join(lines))
    print(f"PE valid encodings: {sum(valid)}/65536")
    print(f"wrote {output} ({output.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
