#!/usr/bin/env python3
"""
Generate c33_forms.h: a per-encoding form table for the emulator.

Decoding is a flat lookup. c33_form_of[insn] gives a form index; the form
carries the operation plus the bit layout of each operand. This sidesteps
mask precedence entirely -- the derived opcode/mask pairs overlap between
forms (srl's 5-bit immediate form has mask 0x5400 over opcode 0x0000, which
would collide with half the ISA) so they cannot drive decoding.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from derive_fields import derive  # noqa: E402


def shape_ident(sh):
    """Stable C identifier for an operand shape.

    The emulator selects addressing modes by comparing this integer. It used
    to strcmp the shape string itself, which profiled as the hottest thing in
    the interpreter: forms are tested as an if/else chain, so a common
    instruction walked several string compares per execution. The string is
    still emitted, but only for the disassembler.
    """
    import re as _re
    if sh == "":
        return "SHAPE_NONE"
    t = sh.replace("%r#", "R").replace("%sp", "SP").replace("%dp", "DP")
    t = t.replace("%psr", "PSR").replace("%alr", "ALR").replace("%ahr", "AHR")
    t = t.replace("%", "").replace("[", "L").replace("]", "B")
    t = t.replace("+", "P").replace(",", "_").replace("#", "I").replace(".", "")
    return "SHAPE_" + _re.sub(r"[^A-Za-z0-9_]", "", t).upper()


def sreg_kind(sh):
    """Classify ld.w special-register forms.

    The executor used to work this out per instruction with strncmp on the
    shape string. It is a property of the encoding, so it belongs here.
      1: ld.w %sreg,%rN   2: ld.w %rN,%sreg   0: neither
    """
    if sh[:1] == "%" and not sh.startswith("%r#"):
        return 1
    if sh.startswith("%r#,") and (sh[4:5] == "%" or sh[4:5] == ""):
        return 2
    return 0


def shape_map(forms):
    """shape string -> unique C identifier, in order of first appearance.

    The empty shape is seeded first so SHAPE_NONE is always value 0, which is
    what the OP_INVALID entry uses.
    """
    names, used = {"": "SHAPE_NONE"}, {"SHAPE_NONE"}
    for f in forms:
        sh = f["shape"]
        if sh in names:
            continue
        n = base = shape_ident(sh)
        k = 2
        while n in used:
            n = f"{base}_{k}"
            k += 1
        used.add(n)
        names[sh] = n
    return names


def op_ident(mnemonic):
    s = mnemonic.upper().replace(".", "_")
    return "OP_" + s


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "allinsn_full.txt"
    out = Path(sys.argv[2] if len(sys.argv) > 2 else "c33_forms.h")

    forms = derive(src)
    bad = [f for f in forms if f["fields"] is None]
    if bad:
        print(f"error: {len(bad)} unsolved forms", file=sys.stderr)
        return 1
    if len(forms) + 1 > 65536:
        print("error: too many forms for uint16_t", file=sys.stderr)
        return 1

    # form 0 is the invalid/.short catch-all
    form_of = [0] * 65536
    for idx, f in enumerate(forms, start=1):
        for e in f["encodings"]:
            form_of[e] = idx

    ops = sorted({f["mnemonic"] for f in forms})
    maxf = max(len(f["fields"]) for f in forms)

    L = [
        "/* Generated by tools/gen_forms.py -- do not edit.",
        " *",
        " * Operand layouts derived empirically by disassembling all 65536",
        " * encodings with c33-epson-elf-objdump and solving each field for",
        " * (shift, width, signed, bias). See derive_fields.py.",
        " */",
        "#ifndef C33_FORMS_H",
        "#define C33_FORMS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define C33_MAX_FIELDS {maxf}",
        "",
        "enum c33_op {",
        "\tOP_INVALID = 0,",
    ]
    for m in ops:
        L.append(f"\t{op_ident(m)},")
    L += ["\tOP_COUNT", "};", ""]

    L.append("static const char *const c33_op_name[OP_COUNT] = {")
    L.append('\t[OP_INVALID] = ".short",')
    for m in ops:
        L.append(f'\t[{op_ident(m)}] = "{m}",')
    L += ["};", ""]

    shapes = shape_map(forms)
    L.append("/* Interned operand shapes: an integer compare in place of strcmp. */")
    L.append("enum c33_shape {")
    for sh in shapes:
        L.append(f"\t{shapes[sh]},")
    L += ["};", ""]

    L += [
        "/* No bias: derive_fields.py solves for one, and it is zero for every",
        "   field in the ISA. The generator asserts that below. */",
        "struct c33_field { uint8_t shift, width, is_signed; };",
        "",
        "struct c33_form {",
        "\tuint8_t  op;",
        "\tuint8_t  nfields;",
        "\tstruct c33_field f[C33_MAX_FIELDS];",
        "\tuint8_t  shape_id;",
        "\tuint8_t  sreg;      /* ld.w special-register form: 0 none, 1 dst, 2 src */",
        "\tconst char *shape;  /* disassembly only */",
        "};",
        "",
        f"static const struct c33_form c33_forms[{len(forms) + 1}] = {{",
        '\t{ OP_INVALID, 0, {{0,0,0}}, SHAPE_NONE, 0, "" },',
    ]
    for f in forms:
        assert all(d == 0 for _, _, _, d in f["fields"]), \
            "a field has a non-zero bias; the runtime struct no longer carries one"
        fl = ", ".join("{%d,%d,%d}" % (a, b, 1 if c else 0)
                       for a, b, c, _ in f["fields"])
        if not fl:
            fl = "{0,0,0}"
        shp = f["shape"].replace("\\", "\\\\").replace('"', '\\"')
        L.append(f'\t{{ {op_ident(f["mnemonic"])}, {len(f["fields"])}, '
                 f'{{{fl}}}, {shapes[f["shape"]]}, '
                 f'{sreg_kind(f["shape"])}, "{shp}" }},')
    L += ["};", ""]

    L.append("/* encoding -> index into c33_forms */")
    assert max(form_of) < 256, "form index no longer fits in a byte"
    # A byte keeps the table at 64K rather than 128K. That matters: 128K is
    # the L1 data cache size on the machines this runs on, so the wider
    # table thrashed it on every decode.
    L.append("static const uint8_t c33_form_of[65536] = {")
    row = []
    for i in range(65536):
        row.append(f"{form_of[i]:4d}")
        if len(row) == 12:
            L.append("\t" + ",".join(row) + ",")
            row = []
    if row:
        L.append("\t" + ",".join(row) + ",")
    L += ["};", "", "#endif /* C33_FORMS_H */"]

    out.write_text("\n".join(L) + "\n")
    covered = sum(1 for v in form_of if v)
    print(f"operations : {len(ops)}")
    print(f"forms      : {len(forms)}")
    print(f"encodings  : {covered}/65536 mapped "
          f"({65536 - covered} invalid)")
    print(f"wrote {out} ({out.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
