#!/usr/bin/env python3
"""Generate the C33 PE valid-encoding bitmap from PE ELF disassembly."""

import re
import sys
from pathlib import Path


def main():
    source = Path(sys.argv[1] if len(sys.argv) > 1 else "allinsn_pe.txt")
    output = Path(sys.argv[2] if len(sys.argv) > 2 else "c33_pe_valid.h")
    valid = [False] * 65536
    seen = set()
    invalid_field_nops = {"ld.w", "pushs", "pops"}

    for line in source.read_text().splitlines():
        match = re.match(
            r"^\s*([0-9a-f]+):\s+([0-9a-f]{2}) ([0-9a-f]{2})\s+(\S+)",
            line,
        )
        if not match:
            continue
        address = int(match.group(1), 16)
        word = int(match.group(3) + match.group(2), 16)
        index = address // 2
        if address & 1 or index >= 65536 or word != index:
            raise ValueError(f"unexpected all-word disassembly line: {line}")
        seen.add(index)
        mnemonic = match.group(4)
        valid[index] = (mnemonic != ".short"
                        and ("***" not in line
                             or mnemonic in invalid_field_nops))

    if len(seen) != 65536:
        raise ValueError(f"found {len(seen)} words, expected 65536")

    bitmap = []
    for base in range(0, 65536, 8):
        bitmap.append(sum(int(valid[base + bit]) << bit for bit in range(8)))

    lines = [
        "/* Generated by tools/gen_pe_valid.py -- do not edit. */",
        "#ifndef C33_PE_VALID_H",
        "#define C33_PE_VALID_H",
        "",
        "#include <stdint.h>",
        "",
        "static const uint8_t c33_pe_valid[8192] = {",
    ]
    for start in range(0, len(bitmap), 16):
        lines.append("\t" + ", ".join(
            f"0x{value:02x}" for value in bitmap[start:start + 16]) + ",")
    lines += ["};", "", "#endif /* C33_PE_VALID_H */", ""]
    output.write_text("\n".join(lines))
    print(f"PE valid encodings: {sum(valid)}/65536")
    print(f"wrote {output} ({output.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
