#!/usr/bin/env python3
"""
Generate an authoritative C33 decode table from binutils' own disassembler.

The opcode table in c33-opc.c drives the *assembler*; the disassembler in
c33-dis.c is an independent hand-written switch (c33_opcodes is commented out
at line 229) and the two disagree -- e.g. srl has an 0x23xx "high immediate"
family that appears nowhere in the assembler table.

Rather than reimplement either, we disassemble all 65536 possible 16-bit
encodings with c33-epson-elf-objdump and turn the result into a flat lookup
table. Decoding is then a single array index that matches objdump by
construction, with no mask-precedence rules to get wrong.

Input:  allinsn.txt   -- "<hex16> <mnemonic>" for every encoding 0000..ffff
Output: c33_optab.h   -- enum of operations + const uint8_t table[65536]
"""

import sys
from pathlib import Path


def ident(mnemonic):
    """Turn a mnemonic into a C identifier: 'ld.w' -> OP_LD_W."""
    if mnemonic == ".short":
        return "OP_INVALID"
    s = mnemonic.upper()
    for ch in ".":
        s = s.replace(ch, "_")
    return "OP_" + s


def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "allinsn.txt")
    out = Path(sys.argv[2] if len(sys.argv) > 2 else "c33_optab.h")

    table = [None] * 65536
    for line in src.read_text().splitlines():
        parts = line.split()
        if len(parts) < 2:
            continue
        table[int(parts[0], 16)] = parts[1]

    missing = [i for i, v in enumerate(table) if v is None]
    if missing:
        print(f"error: {len(missing)} encodings unmapped", file=sys.stderr)
        return 1

    # OP_INVALID must be 0 so a zeroed table reads as invalid
    names = sorted({m for m in table if m != ".short"})
    ids = {".short": 0}
    for i, m in enumerate(names, start=1):
        ids[m] = i

    if len(ids) > 256:
        print(f"error: {len(ids)} ops exceeds uint8_t", file=sys.stderr)
        return 1

    lines = [
        "/* Generated by tools/gen_optab.py -- do not edit.",
        " *",
        " * Derived from c33-epson-elf-objdump by disassembling all 65536",
        " * 16-bit encodings, so this decoder agrees with binutils by",
        " * construction. See gen_optab.py for why the c33-opc.c table is not",
        " * used directly.",
        " */",
        "#ifndef C33_OPTAB_H",
        "#define C33_OPTAB_H",
        "",
        "#include <stdint.h>",
        "",
        "enum c33_op {",
    ]
    for m in [".short"] + names:
        lines.append(f"\t{ident(m):<24s} = {ids[m]:3d},   /* {m} */")
    lines.append("\tOP_COUNT")
    lines.append("};")
    lines.append("")

    lines.append("static const char *const c33_op_name[OP_COUNT] = {")
    for m in [".short"] + names:
        lines.append(f'\t[{ident(m)}] = "{m}",')
    lines.append("};")
    lines.append("")

    lines.append("/* encoding -> enum c33_op */")
    lines.append("static const uint8_t c33_optab[65536] = {")
    row = []
    for i in range(65536):
        row.append(f"{ids[table[i]]:3d}")
        if len(row) == 16:
            lines.append("\t" + ",".join(row) + ",")
            row = []
    lines.append("};")
    lines.append("")
    lines.append("#endif /* C33_OPTAB_H */")

    out.write_text("\n".join(lines) + "\n")
    print(f"distinct operations : {len(ids)}")
    print(f"wrote {out} ({out.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
