#!/usr/bin/env python3
"""
Generate c33_forms.h: a per-encoding form table for the emulator.

Decoding is a flat lookup. c33_form_of[insn] gives a form index; the form
carries the operation plus the bit layout of each operand. This sidesteps
mask precedence entirely -- the derived opcode/mask pairs overlap between
forms (srl's 5-bit immediate form has mask 0x5400 over opcode 0x0000, which
would collide with half the ISA) so they cannot drive decoding.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from derive_fields import derive  # noqa: E402


def op_ident(mnemonic):
    s = mnemonic.upper().replace(".", "_")
    return "OP_" + s


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "allinsn_full.txt"
    out = Path(sys.argv[2] if len(sys.argv) > 2 else "c33_forms.h")

    forms = derive(src)
    bad = [f for f in forms if f["fields"] is None]
    if bad:
        print(f"error: {len(bad)} unsolved forms", file=sys.stderr)
        return 1
    if len(forms) + 1 > 65536:
        print("error: too many forms for uint16_t", file=sys.stderr)
        return 1

    # form 0 is the invalid/.short catch-all
    form_of = [0] * 65536
    for idx, f in enumerate(forms, start=1):
        for e in f["encodings"]:
            form_of[e] = idx

    ops = sorted({f["mnemonic"] for f in forms})
    maxf = max(len(f["fields"]) for f in forms)

    L = [
        "/* Generated by tools/gen_forms.py -- do not edit.",
        " *",
        " * Operand layouts derived empirically by disassembling all 65536",
        " * encodings with c33-epson-elf-objdump and solving each field for",
        " * (shift, width, signed, bias). See derive_fields.py.",
        " */",
        "#ifndef C33_FORMS_H",
        "#define C33_FORMS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define C33_MAX_FIELDS {maxf}",
        "",
        "enum c33_op {",
        "\tOP_INVALID = 0,",
    ]
    for m in ops:
        L.append(f"\t{op_ident(m)},")
    L += ["\tOP_COUNT", "};", ""]

    L.append("static const char *const c33_op_name[OP_COUNT] = {")
    L.append('\t[OP_INVALID] = ".short",')
    for m in ops:
        L.append(f'\t[{op_ident(m)}] = "{m}",')
    L += ["};", ""]

    L += [
        "struct c33_field { uint8_t shift, width, is_signed; int32_t bias; };",
        "",
        "struct c33_form {",
        "\tuint8_t  op;",
        "\tuint8_t  nfields;",
        "\tstruct c33_field f[C33_MAX_FIELDS];",
        "\tconst char *shape;",
        "};",
        "",
        f"static const struct c33_form c33_forms[{len(forms) + 1}] = {{",
        '\t{ OP_INVALID, 0, {{0,0,0,0}}, "" },',
    ]
    for f in forms:
        fl = ", ".join("{%d,%d,%d,%d}" % (a, b, 1 if c else 0, d)
                       for a, b, c, d in f["fields"])
        if not fl:
            fl = "{0,0,0,0}"
        shp = f["shape"].replace("\\", "\\\\").replace('"', '\\"')
        L.append(f'\t{{ {op_ident(f["mnemonic"])}, {len(f["fields"])}, '
                 f'{{{fl}}}, "{shp}" }},')
    L += ["};", ""]

    L.append("/* encoding -> index into c33_forms */")
    L.append("static const uint16_t c33_form_of[65536] = {")
    row = []
    for i in range(65536):
        row.append(f"{form_of[i]:4d}")
        if len(row) == 12:
            L.append("\t" + ",".join(row) + ",")
            row = []
    if row:
        L.append("\t" + ",".join(row) + ",")
    L += ["};", "", "#endif /* C33_FORMS_H */"]

    out.write_text("\n".join(L) + "\n")
    covered = sum(1 for v in form_of if v)
    print(f"operations : {len(ops)}")
    print(f"forms      : {len(forms)}")
    print(f"encodings  : {covered}/65536 mapped "
          f"({65536 - covered} invalid)")
    print(f"wrote {out} ({out.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
