############################################################################
# apps/system/bench/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_SYSTEM_BENCH_PROGNAME)
PRIORITY  = $(CONFIG_SYSTEM_BENCH_PRIORITY)
STACKSIZE = $(CONFIG_SYSTEM_BENCH_STACKSIZE)
MODULE    = $(CONFIG_SYSTEM_BENCH)

MAINSRC = bench_main.c

include $(APPDIR)/Application.mk
