# SPDX-License-Identifier: GPL-2.0
always-$(KBUILD_BUILTIN) += vmlinux.lds

obj-y += head.o setup.o process.o switch.o irq-entry.o irq.o syscall_table.o signal.o clock.o time.o traps.o ptrace.o cpuinfo.o lcd.o devices.o
