#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.0-or-later
"""Embed target headers, examples and bootstrap sources for native builds."""
import json
import sys
from pathlib import Path
root = Path(__file__).resolve().parent

# The compiler sources are a separate checkout; this application carries only
# the NuttX side of the port.  The Makefile passes its location.
tccroot = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else root.parent
lines = ['/* Generated by embed.py. */',
         'static const struct { const char *path, *text; } tcc_files[] = {']
files = []
for folder in ('include', 'examples'):
    for p in sorted((root / folder).rglob('*')):
        if not p.is_file():
            continue
        dest = '/tmp/tcc/include/' + p.relative_to(root / folder).as_posix() if folder == 'include' else '/tmp/' + p.name
        files.append((dest, p))
sources = ('tcc.h tcctok.h elf.h stab.h stab.def dwarf.h libtcc.h libtcc.c tccpp.c '
           'tccgen.c tccdbg.c tccasm.c tccelf.c c33-gen.c c33-link.c c33-run.c').split()
files += [('/tmp/tcc/src/' + name, tccroot / name) for name in sources]
files += [('/tmp/tcc/src/' + name, root / name)
          for name in ('config.h', 'tccdefs_.h', 'bootstrap.c', 'runtime.h')]
for dest, p in files:
    lines.append('{' + json.dumps(dest) + ',')
    lines.extend(json.dumps(line) for line in p.read_text().splitlines(keepends=True))
    lines.append('},')
lines.append('};')
(root / 'tcc_files.h').write_text('\n'.join(lines) + '\n')
