/* GCC software floating-point ABI. SPDX-License-Identifier: LGPL-2.0-or-later */
extern float __addsf3(float, float);
extern float __subsf3(float, float);
extern float __mulsf3(float, float);
extern float __divsf3(float, float);
extern float __negsf2(float);
extern int __eqsf2(float, float);
extern int __nesf2(float, float);
extern int __ltsf2(float, float);
extern int __lesf2(float, float);
extern int __gtsf2(float, float);
extern int __gesf2(float, float);
extern int __unordsf2(float, float);
extern float __floatsisf(int);
extern float __floatunsisf(unsigned int);
extern int __fixsfsi(float);
extern unsigned int __fixunssfsi(float);
extern float __floatdisf(long long);
extern float __floatundisf(unsigned long long);
extern long long __fixsfdi(float);
extern unsigned long long __fixunssfdi(float);
extern double __adddf3(double, double);
extern double __subdf3(double, double);
extern double __muldf3(double, double);
extern double __divdf3(double, double);
extern double __negdf2(double);
extern int __eqdf2(double, double);
extern int __nedf2(double, double);
extern int __ltdf2(double, double);
extern int __ledf2(double, double);
extern int __gtdf2(double, double);
extern int __gedf2(double, double);
extern int __unorddf2(double, double);
extern double __floatsidf(int);
extern double __floatunsidf(unsigned int);
extern int __fixdfsi(double);
extern unsigned int __fixunsdfsi(double);
extern double __floatdidf(long long);
extern double __floatundidf(unsigned long long);
extern long long __fixdfdi(double);
extern unsigned long long __fixunsdfdi(double);
extern double __extendsfdf2(float);
extern float __truncdfsf2(double);
