/* Generated from samo-lib/grifo/src/syscall.list -- do not edit. */
#ifndef C33_SYSCALLS_H
#define C33_SYSCALLS_H

#define C33_SYSCALL_MAX 162

static const char *const c33_syscall_name[C33_SYSCALL_MAX + 1] = {
	[0] = "panic",
	[1] = "debug_print",
	[2] = "debug_print_char",
	[3] = "debug_printf",
	[4] = "debug_hex_dump",
	[16] = "exit",
	[17] = "chain",
	[18] = "power_off",
	[19] = "grifo_reboot",
	[20] = "vector_get",
	[21] = "vector_set",
	[30] = "delay_us",
	[34] = "timer_get",
	[39] = "watchdog",
	[40] = "event_flush",
	[44] = "event_get",
	[45] = "event_wait",
	[46] = "event_peek",
	[50] = "lcd_get_framebuffer",
	[51] = "lcd_set_framebuffer",
	[52] = "lcd_set_default_framebuffer",
	[53] = "lcd_clear",
	[54] = "lcd_get_pixel",
	[55] = "lcd_set_pixel",
	[56] = "lcd_point",
	[57] = "lcd_move_to",
	[58] = "lcd_line_to",
	[60] = "lcd_at_xy",
	[61] = "lcd_print",
	[62] = "lcd_print_char",
	[63] = "lcd_printf",
	[64] = "lcd_set_colour",
	[65] = "lcd_get_colour",
	[66] = "lcd_framebuffer_set_byte",
	[67] = "lcd_framebuffer_get_byte",
	[68] = "lcd_max_columns",
	[69] = "lcd_max_rows",
	[70] = "lcd_window",
	[71] = "lcd_window_get_buffer_size",
	[72] = "lcd_window_get_byte_width",
	[73] = "lcd_window_get_buffer",
	[74] = "lcd_window_set_buffer",
	[75] = "lcd_window_disable",
	[76] = "lcd_window_enable",
	[80] = "lcd_window_clear",
	[81] = "lcd_window_get_pixel",
	[82] = "lcd_window_set_pixel",
	[83] = "lcd_window_set_colour",
	[84] = "lcd_window_get_colour",
	[85] = "lcd_window_point",
	[86] = "lcd_window_move_to",
	[87] = "lcd_window_line_to",
	[90] = "lcd_bitmap",
	[100] = "file_close_all",
	[101] = "file_rename",
	[102] = "file_delete",
	[103] = "file_size",
	[110] = "file_create",
	[111] = "file_open",
	[112] = "file_close",
	[113] = "file_read",
	[114] = "file_write",
	[115] = "file_sync",
	[116] = "file_lseek",
	[122] = "directory_create",
	[123] = "directory_open",
	[124] = "directory_close",
	[125] = "directory_read",
	[126] = "directory_exists",
	[130] = "sector_read",
	[131] = "sector_write",
	[140] = "memory_allocate",
	[141] = "memory_free",
	[142] = "memory_debug",
	[150] = "analog_input",
	[160] = "serial_putchar",
	[161] = "serial_getchar",
	[162] = "serial_inputavailable",
};

#endif /* C33_SYSCALLS_H */
