#!/bin/bash
# Compare the ported assembler against the original binutils 2.10.1 one,
# byte for byte.
#
# The original toolchain is a *byte-exact oracle*: build it with the root
# Makefile's "toolchain" target and it installs to host-tools/toolchain-install.
# This script assembles the same inputs with both and diffs the parts that
# should be identical.
#
#   ./compare-with-oracle.sh [new-binutils-build-dir]
#
# Defaults to host-tools/toolchain-c33/binutils/work/binutils-2.47/build.
#
# Compare the *code*, not the container.  ELF headers, section ordering and
# symbol table layout all differ legitimately between 2.10.1 and 2.47, so
# comparing whole .o files always reports a difference and tells you nothing.

set -u

ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
OLD="${ROOT}/host-tools/toolchain-install/bin"
NEW="${1:-${ROOT}/host-tools/toolchain-c33/binutils/work/binutils-2.47/build}"

OLD_AS="${OLD}/c33-epson-elf-as"
OLD_OBJCOPY="${OLD}/c33-epson-elf-objcopy"
OLD_OBJDUMP="${OLD}/c33-epson-elf-objdump"
NEW_AS="${NEW}/gas/as-new"
NEW_OBJCOPY="${NEW}/binutils/objcopy"
NEW_OBJDUMP="${NEW}/binutils/objdump"

for t in "${OLD_AS}" "${NEW_AS}"; do
	if [ ! -x "${t}" ]; then
		echo "missing: ${t}" >&2
		echo "build the original with 'make toolchain' and the new one with binutils/build.sh" >&2
		exit 1
	fi
done

TMP=$(mktemp -d)
trap 'rm -rf "${TMP}"' EXIT

ASFLAGS="-mc33pe"
text_same=0; text_diff=0
reloc_same=0; reloc_diff=0
data_same=0; data_diff=0
flags_same=0; flags_diff=0
old_fail=0; new_fail=0
diff_list=""

compare_one () {
	local src="$1" inc="$2"

	if ! "${OLD_AS}" ${ASFLAGS} ${inc} -o "${TMP}/old.o" "${src}" 2>/dev/null; then
		old_fail=$((old_fail + 1)); return
	fi
	if ! "${NEW_AS}" ${ASFLAGS} ${inc} -o "${TMP}/new.o" "${src}" 2>/dev/null; then
		new_fail=$((new_fail + 1)); echo "  NEW FAILED: ${src}"; return
	fi

	for sec in .text .data; do
		"${OLD_OBJCOPY}" -O binary --only-section=${sec} "${TMP}/old.o" "${TMP}/old.bin" 2>/dev/null
		"${NEW_OBJCOPY}" -O binary --only-section=${sec} "${TMP}/new.o" "${TMP}/new.bin" 2>/dev/null
		if cmp -s "${TMP}/old.bin" "${TMP}/new.bin"; then
			[ "${sec}" = .text ] && text_same=$((text_same + 1)) || data_same=$((data_same + 1))
		else
			if [ "${sec}" = .text ]; then
				text_diff=$((text_diff + 1)); diff_list="${diff_list} ${src}"
			else
				data_diff=$((data_diff + 1))
			fi
		fi
	done

	# ELF header e_machine and e_flags.  e_flags's top byte records the core variant -- 0 for
	# the base core, 'A' for ADV, 'P' for PE -- and the linker refuses to
	# mix objects that disagree.  Comparing only .text/.data/relocs missed
	# this once: the ported assembler was not setting it at all, and
	# nothing noticed until a firmware link failed.
	# Compared together with e_machine at offset 18, which the original
	# also sets (EM_SE_C33 = 107) and which the port initially did not.
	if [ "$(od -An -tx1 -j 18 -N 2 "${TMP}/old.o")$(od -An -tx1 -j 36 -N 4 "${TMP}/old.o")" \
	   = "$(od -An -tx1 -j 18 -N 2 "${TMP}/new.o")$(od -An -tx1 -j 36 -N 4 "${TMP}/new.o")" ]; then
		flags_same=$((flags_same + 1))
	else
		flags_diff=$((flags_diff + 1))
		echo "  ELF header differs: ${src}"
	fi

	# Relocations: offset, type and symbol.  Note modern gas reduces local
	# symbol references to ".text+offset" where 2.10.1 kept the name; that
	# is a representation difference, not a defect, and resolves identically
	# at link time.
	"${OLD_OBJDUMP}" -r "${TMP}/old.o" 2>/dev/null | grep -E "^[0-9a-f]{8} " | awk '{print $1,$2,$3}' > "${TMP}/old.r"
	"${NEW_OBJDUMP}" -r "${TMP}/new.o" 2>/dev/null | grep -E "^[0-9a-f]{8} " | awk '{print $1,$2,$3}' > "${TMP}/new.r"
	if cmp -s "${TMP}/old.r" "${TMP}/new.r"; then
		reloc_same=$((reloc_same + 1))
	else
		reloc_diff=$((reloc_diff + 1))
	fi
}

echo "== hand-written assembly under samo-lib =="
cd "${ROOT}"
for f in $(find samo-lib -name '*.s' | sort); do
	d=$(dirname "${f}")
	compare_one "${f}" "-I ${d} -I samo-lib/forth -I samo-lib/include"
done

echo
echo "== assembly generated by the original gcc 3.3.2 =="
GEN="${TMP}/gen"; mkdir -p "${GEN}"
OLD_GCC="${OLD}/c33-epson-elf-gcc"
if [ -x "${OLD_GCC}" ]; then
	for c in $(find samo-lib wiki -name '*.c' 2>/dev/null | sort); do
		o="${GEN}/$(echo "${c}" | tr '/' '_' | sed 's/\.c$/.s/')"
		"${OLD_GCC}" -S -Os -mc33pe -mlong-calls -fno-builtin \
			-I samo-lib/include -I samo-lib/grifo/include \
			-I samo-lib/mini-libc/include \
			-I samo-lib/fatfs/config/c33/read-write \
			-I "$(dirname "${c}")" -o "${o}" "${c}" 2>/dev/null || continue
		# gcc 3.3.2 emits ".size .foo,.-.foo" with a stray leading dot.
		# binutils 2.10.1 accepted it and quietly invented a bogus undefined
		# symbol; modern gas rejects it.  Normalise so we compare encodings
		# rather than that known compiler bug.
		sed -E 's/^([[:space:]]*\.size[[:space:]]+)\.([A-Za-z_][A-Za-z0-9_]*),\.-\.([A-Za-z_][A-Za-z0-9_]*)/\1\2,.-\3/' \
			"${o}" > "${o}.fixed" && mv "${o}.fixed" "${o}"
		compare_one "${o}" ""
	done
else
	echo "  (original gcc not found, skipping)"
fi

echo
echo "results"
echo "  .text  identical ${text_same}   differing ${text_diff}"
echo "  .data  identical ${data_same}   differing ${data_diff}"
echo "  relocs identical ${reloc_same}   differing ${reloc_diff}"
echo "  e_machine+e_flags identical ${flags_same}   differing ${flags_diff}"
echo "  old assembler failed on ${old_fail} (expected: forth/trailer.s is a cat fragment)"
echo "  new assembler failed on ${new_fail}"
[ -n "${diff_list}" ] && { echo "  .text differs in:"; for f in ${diff_list}; do echo "    ${f}"; done; }

[ "${text_diff}" -eq 0 ] && [ "${new_fail}" -eq 0 ] && [ "${flags_diff}" -eq 0 ]
