#!/usr/bin/env python3
"""Register the Seiko Epson C33 target across a modern binutils tree.

Idempotent: safe to re-run.  Edits both Makefile.am and the generated
Makefile.in / configure, because binutils 2.47 ships files generated by
automake 1.15.1 and regenerating with a newer automake produces enormous
unrelated churn.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else '.')
changed, skipped = [], []


def edit(relpath, fn):
    p = ROOT / relpath
    if not p.exists():
        print(f'  !! missing {relpath}')
        return
    src = p.read_text(encoding='latin-1')
    out = fn(src)
    if out is None or out == src:
        skipped.append(relpath)
    else:
        p.write_text(out, encoding='latin-1')
        changed.append(relpath)


def after(src, anchor, addition, guard):
    """Insert `addition` immediately after the line containing `anchor`."""
    if guard in src:
        return None
    i = src.index(anchor)
    eol = src.index('\n', i) + 1
    return src[:eol] + addition + src[eol:]


# ---------------------------------------------------------------- bfd/archures
edit('bfd/archures.c', lambda s: after(
    s, '.  bfd_arch_v850,      {* NEC V850.  *}',
    '.  bfd_arch_c33,       {* Seiko Epson C33 (S1C33 family).  *}\n',
    'bfd_arch_c33,'))

edit('bfd/archures.c', lambda s: after(
    s, 'extern const bfd_arch_info_type bfd_v850_arch;',
    'extern const bfd_arch_info_type bfd_c33_arch;\n',
    'bfd_c33_arch;'))

edit('bfd/archures.c', lambda s: after(
    s, '    &bfd_v850_arch,',
    '    &bfd_c33_arch,\n',
    '&bfd_c33_arch,'))

# bfd-in2.h is generated from archures.c by "make headers"; keep it in sync by
# hand so the tree builds without maintainer-mode tooling.
edit('bfd/bfd-in2.h', lambda s: after(
    s, '  bfd_arch_v850,      /* NEC V850.  */',
    '  bfd_arch_c33,       /* Seiko Epson C33 (S1C33 family).  */\n',
    'bfd_arch_c33,'))

# ----------------------------------------------------------------- bfd/targets
edit('bfd/targets.c', lambda s: after(
    s, 'extern const bfd_target v850_elf32_vec;',
    'extern const bfd_target c33_elf32_vec;\n',
    'extern const bfd_target c33_elf32_vec;'))

edit('bfd/targets.c', lambda s: after(
    s, '\t&v850_elf32_vec,',
    '\n\t&c33_elf32_vec,\n',
    '&c33_elf32_vec,'))

# --------------------------------------------------------------- bfd/config.bfd
def config_bfd(s):
    if 'c33_elf32_vec' in s:
        return None
    s = s.replace(
        '  v850*-*-*)\n',
        '  c33-*-*)\n'
        '    targ_defvec=c33_elf32_vec\n'
        '    ;;\n'
        '\n'
        '  v850*-*-*)\n', 1)
    return s


edit('bfd/config.bfd', config_bfd)


# ------------------------------------------------------------- bfd/Makefile.{am,in}
def bfd_make(s):
    if 'cpu-c33.' in s:
        return None
    s = s.replace('\tcpu-v850.lo \\', '\tcpu-c33.lo \\\n\tcpu-v850.lo \\', 1)
    s = s.replace('\tcpu-v850.c \\', '\tcpu-c33.c \\\n\tcpu-v850.c \\', 1)
    s = s.replace('\telf32-v850.lo \\', '\telf32-c33.lo \\\n\telf32-v850.lo \\', 1)
    s = s.replace('\telf32-v850.c \\', '\telf32-c33.c \\\n\telf32-v850.c \\', 1)
    return s


for f in ('bfd/Makefile.am', 'bfd/Makefile.in'):
    edit(f, bfd_make)


# ------------------------------------------------------------------- opcodes
def opc_configure(s):
    if 'bfd_c33_arch' in s:
        return None
    return s.replace(
        '\tbfd_v850_arch)\t\tta="$ta v850-opc.lo v850-dis.lo" ;;',
        '\tbfd_c33_arch)\t\tta="$ta c33-opc.lo c33-dis.lo" ;;\n'
        '\tbfd_v850_arch)\t\tta="$ta v850-opc.lo v850-dis.lo" ;;', 1)


edit('opcodes/configure.ac', opc_configure)
edit('opcodes/configure', opc_configure)


def opc_make(s):
    if 'c33-dis.' in s:
        return None
    s = s.replace('\tv850-dis.c \\', '\tc33-dis.c \\\n\tc33-opc.c \\\n\tv850-dis.c \\', 1)
    return s


for f in ('opcodes/Makefile.am', 'opcodes/Makefile.in'):
    edit(f, opc_make)

edit('opcodes/disassemble.h', lambda s: after(
    s, 'extern int print_insn_v850\t\t(bfd_vma, disassemble_info *);',
    'extern int print_insn_c33\t\t(bfd_vma, disassemble_info *);\n',
    'print_insn_c33'))


def dis_c(s):
    if 'ARCH_c33' in s:
        return None
    s = s.replace('#define ARCH_v850\n', '#define ARCH_c33\n#define ARCH_v850\n', 1)
    s = s.replace(
        '#ifdef ARCH_v850\n    case bfd_arch_v850:',
        '#ifdef ARCH_c33\n'
        '    case bfd_arch_c33:\n'
        '      disassemble = print_insn_c33;\n'
        '      break;\n'
        '#endif\n'
        '#ifdef ARCH_v850\n'
        '    case bfd_arch_v850:', 1)
    return s


edit('opcodes/disassemble.c', dis_c)

# ----------------------------------------------------------------------- gas
edit('gas/configure.tgt', lambda s: after(
    s, '  v850*)\t\tcpu_type=v850 ;;',
    '  c33*)\t\t\tcpu_type=c33 ;;\n',
    'cpu_type=c33'))

edit('gas/configure.tgt', lambda s: after(
    s, '  v850*-*-*)\t\t\t\tfmt=elf ;;',
    '  c33-*-*)\t\t\t\tfmt=elf ;;\n',
    'c33-*-*)\t\t\t\tfmt=elf'))


def gas_make(s):
    if 'tc-c33.c' in s:
        return None
    s = s.replace('\tconfig/tc-v850.c \\', '\tconfig/tc-c33.c \\\n\tconfig/tc-v850.c \\', 1)
    s = s.replace('\tconfig/tc-v850.h \\', '\tconfig/tc-c33.h \\\n\tconfig/tc-v850.h \\', 1)
    return s


for f in ('gas/Makefile.am', 'gas/Makefile.in'):
    edit(f, gas_make)

# ------------------------------------------------------------------------ ld
edit('ld/configure.tgt', lambda s: after(
    s, 'v850*-*-*)\t\ttarg_emul=v850_rh850',
    '', 'c33-*-*)') if 'c33-*-*)' in s else s.replace(
    'v850*-*-*)\t\ttarg_emul=v850_rh850',
    'c33-*-*)\t\ttarg_emul=c33\n\t\t\t;;\n'
    'v850*-*-*)\t\ttarg_emul=v850_rh850', 1))


def ld_make(s):
    if 'ec33.c' in s:
        return None
    return s.replace('\tev850.c \\', '\tec33.c \\\n\tev850.c \\', 1)


for f in ('ld/Makefile.am', 'ld/Makefile.in'):
    edit(f, ld_make)

print('changed:')
for c in changed:
    print('  +', c)
print(f'unchanged/already-done: {len(skipped)}')

# ------------------- bfd/configure{,.ac}: target vector -> object mapping -----
def bfd_vecmap(s):
    if 'c33_elf32_vec)' in s:
        return None
    return s.replace(
        '    v850_elf32_vec)\t\t tb="$tb elf32-v850.lo elf32.lo $elf" ;;',
        '    c33_elf32_vec)\t\t tb="$tb elf32-c33.lo elf32.lo $elf" ;;\n'
        '    v850_elf32_vec)\t\t tb="$tb elf32-v850.lo elf32.lo $elf" ;;', 1)


for f in ('bfd/configure.ac', 'bfd/configure'):
    edit(f, bfd_vecmap)

print('vecmap pass:', changed[-2:])

# ---------------- BFD relocation codes for C33 --------------------------------
# Order MUST be identical in bfd-in2.h (the enum) and libbfd.h (the name table);
# reloc.c is the upstream source of truth that generates both.
C33_RELOCS = [
    'AH', 'AL', 'RH', 'RM', 'RL', 'H', 'M', 'L', 'DH', 'DL', 'GL',
    'SH', 'SL', 'TH', 'TL', 'ZH', 'ZL', 'DPH', 'DPM', 'DPL',
    'LOOP', 'JP', 'S_RH', 'S_RM', 'S_RL',
    'PUSHN_R0', 'PUSHN_R1', 'PUSH_R1', 'CALLT_16_16_OFFSET',
]
C33_RELOC_NAMES = [f'BFD_RELOC_C33_{r}' for r in C33_RELOCS]


def reloc_c(s):
    if 'BFD_RELOC_C33_AH' in s:
        return None
    body = 'ENUM\n  ' + C33_RELOC_NAMES[0] + '\n'
    body += ''.join(f'ENUMX\n  {n}\n' for n in C33_RELOC_NAMES[1:])
    body += ('ENUMDOC\n'
             '  Seiko Epson C33 (S1C33 family) relocations.  The H/M/L and\n'
             '  RH/RM/RL families split a 32-bit value across the multiple\n'
             '  immediate fields produced by the "ext" prefix mechanism; the\n'
             '  G/S/T/Z variants are relative to the global, small, tiny and\n'
             '  zero data area base registers respectively.\n')
    return s.replace('ENUM\n  BFD_RELOC_V850_9_PCREL\n', body + 'ENUM\n  BFD_RELOC_V850_9_PCREL\n', 1)


edit('bfd/reloc.c', reloc_c)


def bfd_in2(s):
    if 'BFD_RELOC_C33_AH' in s:
        return None
    body = ''.join(f'  {n},\n' for n in C33_RELOC_NAMES)
    return s.replace('  BFD_RELOC_V850_9_PCREL,\n', body + '  BFD_RELOC_V850_9_PCREL,\n', 1)


edit('bfd/bfd-in2.h', bfd_in2)


def libbfd_h(s):
    if 'BFD_RELOC_C33_AH' in s:
        return None
    body = ''.join(f'  "{n}",\n' for n in C33_RELOC_NAMES)
    return s.replace('  "BFD_RELOC_V850_9_PCREL",\n', body + '  "BFD_RELOC_V850_9_PCREL",\n', 1)


edit('bfd/libbfd.h', libbfd_h)

print('reloc pass done')

# -------- C33-specific bfd_reloc_status_type values ---------------------------
# The C33 small-data-area relocations report their own overflow conditions so
# the linker can name the offending area (global/small/tiny/zero/dp).
C33_STATUS = [
    'bfd_reloc_over_doff_globalpointer', 'bfd_reloc_over_goff_globalpointer',
    'bfd_reloc_over_soff_globalpointer', 'bfd_reloc_over_toff_globalpointer',
    'bfd_reloc_over_zoff_globalpointer',
    'bfd_reloc_doff_over_64mb', 'bfd_reloc_doff_over_8kb',
    'bfd_reloc_goff_over_8kb',
    'bfd_reloc_soff_over_64mb', 'bfd_reloc_soff_over_8kb',
    'bfd_reloc_toff_over_64mb', 'bfd_reloc_toff_over_8kb',
    'bfd_reloc_zoff_over_64mb', 'bfd_reloc_zoff_over_8kb',
    'bfd_reloc_dpoff_over_512kb', 'bfd_reloc_dpoff_over_64b',
]


def status_bfd_in2(s):
    if C33_STATUS[0] in s:
        return None
    body = ('\n  /* Seiko Epson C33 data-area overflow conditions.  */\n'
            + ''.join(f'  {n},\n' for n in C33_STATUS))
    return s.replace('  bfd_reloc_dangerous\n }\n bfd_reloc_status_type;',
                     '  bfd_reloc_dangerous,\n' + body + ' }\n bfd_reloc_status_type;', 1)


edit('bfd/bfd-in2.h', status_bfd_in2)


def status_reloc_c(s):
    if C33_STATUS[0] in s:
        return None
    body = ('.\n.  {* Seiko Epson C33 data-area overflow conditions.  *}\n'
            + ''.join(f'.  {n},\n' for n in C33_STATUS))
    return s.replace('.  bfd_reloc_dangerous\n', '.  bfd_reloc_dangerous,\n' + body, 1)


edit('bfd/reloc.c', status_reloc_c)

print('status pass done')

# ---------------- gas: build ext_remove.c for the c33 target ------------------
# ext_remove.c implements the second assembly pass that strips redundant "ext"
# prefixes.  Wire it in the way bfin wires its parser: list it as an extra
# source so automake emits a rule, then pull the object in via extra_objects.
def gas_make_ext(s):
    if 'ext_remove.c' in s:
        return None
    s = s.replace('\tconfig/tc-c33.c \\', '\tconfig/tc-c33.c \\\n\text_remove.c \\', 1)
    s = s.replace('\tconfig/tc-c33.h \\', '\tconfig/tc-c33.h \\\n\text_remove.h \\', 1)
    return s


for f in ('gas/Makefile.am', 'gas/Makefile.in'):
    edit(f, gas_make_ext)


def gas_extra_objects(s):
    if 'ext_remove.o' in s:
        return None
    return s.replace(
        '      bfin)\n',
        '      c33)\n'
        '\tfor f in ext_remove.o; do\n'
        '\t  case " $extra_objects " in\n'
        '\t    *" $f "*) ;;\n'
        '\t    *) extra_objects="$extra_objects $f" ;;\n'
        '\t  esac\n'
        '\tdone\n'
        '\t;;\n'
        '\n'
        '      bfin)\n', 1)


for f in ('gas/configure.ac', 'gas/configure'):
    edit(f, gas_extra_objects)

print('gas ext_remove wiring done')
