#!/usr/bin/env python3
"""Generate nuttx.xpm, the Grifo launcher icon, from the upstream logo.

The source is nuttx-logo.png, taken from the NuttX tree's
Documentation/logos.  The logo belongs to the Apache Software Foundation;
this identifies the NuttX entry in the launcher and claims nothing else.

Two things make it harder to reduce than the DOOM wordmark beside it:

  - It is shaded, 14.6% mid-tone over more than a thousand colours, so the
    alpha channel cannot be the shape the way it can for flat art.  Taken
    as a silhouette the mark is a solid diamond and its whole design -- the
    interlocking angular pieces -- disappears, because that design is drawn
    in colour inside an opaque outline.  The split has to be by luminance:
    the blues are dark, the highlights and the gaps are light.

  - It is a mark above a wordmark.  At 64 pixels the wordmark would be six
    pixels tall and unreadable, so only the mark is used, found by the
    blank rows between them and squared up before reducing.

Regenerating needs Pillow; the checked-in XPM does not.
"""
import argparse
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
SIZE = 64
INK = 150          # luminance: the logo's blues fall well below, its
                   # highlights and gaps well above


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--logo', type=Path, default=HERE / 'nuttx-logo.png')
    parser.add_argument('--out', type=Path, default=HERE / 'nuttx.xpm')
    args = parser.parse_args()

    from PIL import Image
    import numpy as np

    image = Image.open(args.logo).convert('RGBA')
    white = Image.new('RGBA', image.size, (255, 255, 255, 255))
    flat = Image.alpha_composite(white, image).convert('L')

    ink = np.array(flat).astype(int) < INK
    used = np.where(ink.any(axis=1))[0]
    blank = [y for y in range(used.min(), used.max()) if not ink[y].any()]
    bottom = blank[0] if blank else flat.size[1]      # the mark ends here
    mark = flat.crop((0, 0, flat.size[0], bottom))
    columns = np.where((np.array(mark).astype(int) < INK).any(axis=0))[0]
    mark = mark.crop((columns.min(), 0, columns.max() + 1, bottom))

    side = max(mark.size)
    square = Image.new('L', (side, side), 255)
    square.paste(mark, ((side - mark.size[0]) // 2, (side - mark.size[1]) // 2))

    inner = SIZE - 2                                   # a pixel of air around it
    canvas = Image.new('L', (SIZE, SIZE), 255)
    canvas.paste(square.resize((inner, inner), Image.BOX), (1, 1))

    rows = ['"' + ''.join('#' if canvas.getpixel((x, y)) < INK else '.'
                          for x in range(SIZE)) + '"' for y in range(SIZE)]
    args.out.write_text(
        '/* XPM: the Apache NuttX logo, for the Grifo launcher.\n'
        '   Generated by make-icon.py from nuttx-logo.png; edit that. */\n'
        'static char *nuttx_icon[] = {\n'
        '"64 64 2 1",\n". c #FFFFFF",\n"# c #000000",\n'
        + ',\n'.join(rows) + '\n};\n')
    print(args.out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
