#!/usr/bin/env python3
"""Generate doom.xpm, the Grifo launcher icon, from the DOOM wordmark.

The source is doom-logo.webp: 3840x1987, pure black with an alpha channel,
0.24% mid-tone.  That makes this a straightforward reduction with nothing
to tune -- the alpha channel *is* the shape, so there is no figure to
separate from a ground, and flat art means area coverage cut at exactly
half gives the right answer.  (The Tux icon in riscv/ was hard for exactly
the opposite reasons: its source was dithered and drew Tux the same colour
as the background it sat on.)

The wordmark is close to 2:1, so it fits the icon's width and sits centred
in the 64x64 square.

The DOOM logo is id Software's; this identifies the game the entry
launches, and the port itself uses PureDOOM.  Regenerating needs Pillow;
the checked-in XPM does not.
"""
import argparse
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
SIZE = 64


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--logo', type=Path, default=HERE / 'doom-logo.webp')
    parser.add_argument('--out', type=Path, default=HERE / 'doom.xpm')
    args = parser.parse_args()

    from PIL import Image

    image = Image.open(args.logo).convert('RGBA')
    width, height = image.size
    # The alpha channel is the artwork; the colour is a uniform black.
    shape = image.getchannel('A')
    scaled_h = max(1, round(height * SIZE / width))
    small = shape.resize((SIZE, scaled_h), Image.BOX)

    canvas = Image.new('L', (SIZE, SIZE), 0)
    canvas.paste(small, (0, (SIZE - scaled_h) // 2))

    rows = []
    for y in range(SIZE):
        rows.append('"' + ''.join('#' if canvas.getpixel((x, y)) >= 128 else '.'
                                  for x in range(SIZE)) + '"')
    args.out.write_text(
        '/* XPM: the DOOM wordmark, for the Grifo launcher.\n'
        '   Generated by make-icon.py from doom-logo.webp; edit that. */\n'
        'static char *doom_icon[] = {\n'
        '"64 64 2 1",\n". c #FFFFFF",\n"# c #000000",\n'
        + ',\n'.join(rows) + '\n};\n')
    print(args.out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
