# Firmware-level timed event-wait test; needs the current Grifo kernel.
ROOT_DIR := $(abspath ../../..)
MK_DIR := $(ROOT_DIR)/samo-lib/Mk
include $(MK_DIR)/definitions.mk
include $(GRIFO_APPLICATION_PRE)
PROGRAM = idle_wait
include $(GRIFO_APPLICATION_POST)
